'use client';

import { useState } from 'react';
import { LabFramework, MetricRow, SliderControl } from './LabFramework';
import { cn } from '@/lib/utils';

export function CdnLab() {
  const [users, setUsers] = useState(10000), [edgeHit, setEdgeHit] = useState(85), [originMs, setOriginMs] = useState(140), [regions, setRegions] = useState(3);
  const originRps = Math.round(users * (1 - edgeHit / 100));
  const latency = Math.max(8, Math.round(originMs * (1 - edgeHit / 160) + 12));
  return <LabFramework eyebrow="Lab 06 · CDN" title="CDN Traffic Lab" subtitle="See how edge caching changes latency, origin load, and regional fan-out." problem={<span>Move traffic closer to users instead of forcing every request through one origin.</span>} canvas={<div className="lab-visual-stack"><div className="lab-architecture-row"><div className="lab-node">Users<br/><small>{users.toLocaleString()}</small></div><div className="lab-arrow">→</div><div className="lab-node lab-node--accent">Edge POPs<br/><small>{regions} regions</small></div><div className="lab-arrow">→</div><div className="lab-node">Origin<br/><small>{originRps}/s</small></div></div><div className="lab-flow-bar"><div style={{width:`${edgeHit}%`}} className="lab-flow-bar__fill" /><span>{edgeHit}% edge hit</span></div></div>} controls={<><SliderControl label="Requests/s" value={users} min={1000} max={100000} unit=" req/s" onChange={setUsers}/><SliderControl label="Edge hit rate" value={edgeHit} min={0} max={99} unit="%" onChange={setEdgeHit}/><SliderControl label="Origin latency" value={originMs} min={20} max={500} unit=" ms" onChange={setOriginMs}/><SliderControl label="Regions" value={regions} min={1} max={8} unit="" onChange={setRegions}/></>} metrics={<><MetricRow label="Origin load" value={`${originRps.toLocaleString()} req/s`} tone={originRps > users*0.4 ? 'danger' : originRps > users*0.2 ? 'warning' : 'success'}/><MetricRow label="Estimated user latency" value={`${latency} ms`} tone={latency > 100 ? 'warning' : 'success'}/><MetricRow label="Edge-served" value={`${(users-originRps).toLocaleString()} req/s`} tone="success"/></>} explanation={<span>Raising the hit rate keeps more requests at the edge, so the origin sees less traffic. A CDN is not just a speed trick: it also reduces origin saturation and absorbs traffic bursts.</span>} guidedScenario={{title:'Black Friday',description:'Push traffic to 80,000 req/s, then lower the edge hit rate to 50%. Watch the origin load explode.',action:{label:'Try scenario',onClick:()=>{setUsers(80000);setEdgeHit(50);setRegions(6)}},question:'What would you protect next if the origin still became the bottleneck?'}} takeaway={<span>Cache close to users first when content is repeatable. Then design the origin for the misses that remain.</span>} relatedConcepts={[{slug:'cdn',title:'Content Delivery Networks'},{slug:'cdn-caching',title:'CDN Caching'},{slug:'load-balancers',title:'Load Balancers'}]} onReset={()=>{setUsers(10000);setEdgeHit(85);setOriginMs(140);setRegions(3)}} />
}

export function CircuitBreakerLab() {
  const [failureRate,setFailureRate]=useState(20), [threshold,setThreshold]=useState(5), [retries,setRetries]=useState(2);
  const open = failureRate >= threshold * 8;
  const amplified = Math.min(100, failureRate * (1 + retries));
  return <LabFramework eyebrow="Lab 07 · Reliability" title="Circuit Breaker Lab" subtitle="See how retries can make a failing dependency even worse — and how a circuit breaker changes the pressure." problem={<span>A downstream service is failing. Your service must stop turning a dependency failure into a cascading failure.</span>} canvas={<div className="lab-breaker"><div className="lab-breaker__state" data-open={open}>{open ? 'OPEN' : 'CLOSED'}</div><div className="lab-breaker__flow"><span>Caller</span><span>→</span><span>Breaker</span><span>→</span><span>Dependency</span></div><div className="lab-breaker__meter"><div style={{width:`${amplified}%`}}/></div></div>} controls={<><SliderControl label="Dependency failure" value={failureRate} min={0} max={100} unit="%" onChange={setFailureRate}/><SliderControl label="Open threshold" value={threshold} min={1} max={20} unit=" failures" onChange={setThreshold}/><SliderControl label="Retries" value={retries} min={0} max={4} unit="x" onChange={setRetries}/></>} metrics={<><MetricRow label="Effective pressure" value={`${amplified}%`} tone={amplified>75?'danger':amplified>45?'warning':'success'}/><MetricRow label="Breaker state" value={open?'OPEN':'CLOSED'} tone={open?'success':'default'}/><MetricRow label="Retry amplification" value={`${1+retries}×`} tone={retries>1?'warning':'default'}/></>} explanation={<span>Retries can multiply traffic toward a dependency that is already unhealthy. An open breaker cuts that feedback loop and lets the caller fail fast or degrade gracefully.</span>} guidedScenario={{title:'Dependency outage',description:'Raise dependency failure above 80%, then add retries. Notice how pressure rises while the breaker protects the dependency.',action:{label:'Break the dependency',onClick:()=>{setFailureRate(90);setThreshold(5);setRetries(3)}},question:'What should happen to user experience while the breaker is open?'}} takeaway={<span>Retries help transient failures. Circuit breakers protect you when the failure is persistent.</span>} relatedConcepts={[{slug:'circuit-breaker',title:'Circuit Breaker'},{slug:'retry',title:'Retry'},{slug:'graceful-degradation',title:'Graceful Degradation'}]} onReset={()=>{setFailureRate(20);setThreshold(5);setRetries(2)}} />
}

export function ConsistentHashingLab() {
  const [nodes,setNodes]=useState(4),[virtualNodes,setVirtualNodes]=useState(32),[keys,setKeys]=useState(1000);
  const movement = Math.round((100 / nodes) * Math.max(1, 1 - virtualNodes / 64) * 0.95);
  return <LabFramework eyebrow="Lab 08 · Partitioning" title="Consistent Hashing Lab" subtitle="Add and remove nodes from a hash ring and see how much key movement you really incur." problem={<span>Naive modulo hashing remaps most keys when the server count changes. A ring reduces the amount of data that needs to move.</span>} canvas={<div className="hash-ring-wrap"><div className="hash-ring"><span className="hash-ring__node node-a">A</span><span className="hash-ring__node node-b">B</span><span className="hash-ring__node node-c">C</span><span className="hash-ring__node node-d">D</span>{Array.from({length:Math.min(12,Math.max(2,Math.round(virtualNodes/4)))},(_,i)=><i key={i} style={{transform:`rotate(${i*(360/Math.min(12,Math.max(2,Math.round(virtualNodes/4))))}deg) translateY(-94px)`}} />)}</div><div className="hash-ring-caption">{nodes} nodes · {virtualNodes} virtual nodes/node</div></div>} controls={<><SliderControl label="Physical nodes" value={nodes} min={2} max={8} unit="" onChange={setNodes}/><SliderControl label="Virtual nodes" value={virtualNodes} min={8} max={128} unit=" / node" onChange={setVirtualNodes}/><SliderControl label="Keys" value={keys} min={100} max={10000} unit="" onChange={setKeys}/></>} metrics={<><MetricRow label="Estimated moved keys" value={`${Math.round(keys*movement/100).toLocaleString()}`} tone="warning"/><MetricRow label="Approx movement" value={`${movement}%`} tone={movement<15?'success':'warning'}/><MetricRow label="Ring points" value={(nodes*virtualNodes).toLocaleString()} tone="default"/></>} explanation={<span>More virtual nodes smooth the distribution of keys around the ring. When a node joins or leaves, only the neighboring key ranges need to move rather than the entire dataset.</span>} guidedScenario={{title:'Add a node',description:'Increase the physical node count from 4 to 5. Then compare the moved-key estimate with a naive modulo approach.',action:{label:'Add node',onClick:()=>setNodes(5)},question:'Why does consistent hashing reduce remapping instead of eliminating it?'}} takeaway={<span>Consistent hashing trades a little ring-management complexity for dramatically less reshuffling when topology changes.</span>} relatedConcepts={[{slug:'consistent-hashing',title:'Consistent Hashing'},{slug:'sharding',title:'Sharding'}]} onReset={()=>{setNodes(4);setVirtualNodes(32);setKeys(1000)}} />
}

export function CapacityLab() {
  const [daily,setDaily]=useState(10000000),[peak,setPeak]=useState(4),[payload,setPayload]=useState(4);
  const avg = daily/86400; const p=avg*peak; const bandwidth=(p*payload*8)/1000;
  return <LabFramework eyebrow="Lab 09 · Estimation" title="Capacity Planning Lab" subtitle="Turn product assumptions into rough QPS, bandwidth, and storage numbers before choosing components." problem={<span>System design starts with an order-of-magnitude estimate. The goal is not precision — it is exposing whether an architecture is even plausible.</span>} canvas={<div className="capacity-tiles"><div><span>Avg QPS</span><strong>{avg.toFixed(1)}</strong></div><div><span>Peak QPS</span><strong>{Math.round(p).toLocaleString()}</strong></div><div><span>Peak bandwidth</span><strong>{bandwidth.toFixed(1)} Mbps</strong></div></div>} controls={<><SliderControl label="Requests/day" value={daily} min={100000} max={100000000} unit="" onChange={setDaily}/><SliderControl label="Peak multiplier" value={peak} min={1} max={12} unit="x" onChange={setPeak}/><SliderControl label="Payload size" value={payload} min={1} max={64} unit=" KB" onChange={setPayload}/></>} metrics={<><MetricRow label="Average QPS" value={avg.toFixed(1)} tone="default"/><MetricRow label="Peak QPS" value={Math.round(p).toLocaleString()} tone={p>5000?'danger':p>1000?'warning':'success'}/><MetricRow label="Peak bandwidth" value={`${bandwidth.toFixed(1)} Mbps`} tone="default"/><MetricRow label="30-day raw request volume" value={`${(daily*30/1e6).toFixed(1)}M`} tone="default"/></>} explanation={<span>Start with volume, divide by seconds, then apply a peak multiplier. Payload size turns request rate into a rough bandwidth target. Every later architecture choice should be consistent with these numbers.</span>} guidedScenario={{title:'Traffic spike',description:'Set peak traffic to 10× and payload to 16 KB. Decide whether one server, a CDN, or a load-balanced fleet makes sense.',action:{label:'Simulate spike',onClick:()=>{setPeak(10);setPayload(16)}},question:'Which estimate would you calculate next: storage, cache size, or database connections?'}} takeaway={<span>Back-of-the-envelope math is the bridge between a product requirement and a credible architecture.</span>} relatedConcepts={[{slug:'capacity-estimation',title:'Capacity Estimation'},{slug:'bandwidth-estimation',title:'Bandwidth Estimation'},{slug:'cache-sizing',title:'Cache Sizing'}]} onReset={()=>{setDaily(10000000);setPeak(4);setPayload(4)}} />
}

export function ShardingLab() {
  const [shards,setShards]=useState(4),[writes,setWrites]=useState(4000),[skew,setSkew]=useState(10);
  const ideal=writes/shards; const hot=Math.round(ideal*(1+skew/20));
  return <LabFramework eyebrow="Lab 10 · Data" title="Sharding Lab" subtitle="See how shard count and key skew affect write distribution and the hottest partition." problem={<span>A single database eventually becomes the bottleneck. Sharding spreads the dataset and workload, but a bad partition key can still create a hot shard.</span>} canvas={<div className="shard-grid">{Array.from({length:shards},(_,i)=><div key={i} className={cn('shard-card',i===0&&skew>35&&'shard-card--hot')}><span>Shard {i+1}</span><strong>{Math.round(i===0?hot:ideal)} w/s</strong><small>{i===0&&skew>35?'hot partition':'healthy'}</small></div>)}</div>} controls={<><SliderControl label="Shards" value={shards} min={2} max={8} unit="" onChange={setShards}/><SliderControl label="Total writes" value={writes} min={500} max={20000} unit=" w/s" onChange={setWrites}/><SliderControl label="Key skew" value={skew} min={0} max={80} unit="%" onChange={setSkew}/></>} metrics={<><MetricRow label="Ideal writes / shard" value={`${Math.round(ideal)} w/s`} tone="success"/><MetricRow label="Hot shard" value={`${hot} w/s`} tone={hot>ideal*1.5?'danger':hot>ideal*1.2?'warning':'success'}/><MetricRow label="Shard count" value={`${shards}`} tone="default"/></>} explanation={<span>A good partition key keeps load balanced. Increasing shard count gives more capacity, but a hot key can still concentrate traffic on one partition.</span>} guidedScenario={{title:'Hot celebrity key',description:'Push skew above 60%. Notice how the hottest shard becomes the real bottleneck even though total capacity increased.',action:{label:'Create hot key',onClick:()=>setSkew(70)},question:'How would you fix the hot key without rebuilding the entire dataset?'}} takeaway={<span>Sharding increases capacity only if the partitioning strategy keeps the work distributed.</span>} relatedConcepts={[{slug:'sharding',title:'Sharding'},{slug:'consistent-hashing',title:'Consistent Hashing'},{slug:'denormalization',title:'Denormalization'}]} onReset={()=>{setShards(4);setWrites(4000);setSkew(10)}} />
}
