#!/usr/bin/env python3
"""Generate remaining priority concepts: back-pressure, idempotency, consistent-hashing, rate-limiting, task-queues, sql-vs-nosql, replication, sharding, microservices, tcp, udp."""
import json, os
CONCEPTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'content', 'concepts')

def write_concept(slug, data):
    fpath = os.path.join(CONCEPTS_DIR, f'{slug}.json')
    with open(fpath, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write('\n')
    print(f'  Wrote {slug} ({len(data.get("blocks",[]))} blocks)')

write_concept('idempotent-operations', {
    "slug": "idempotent-operations",
    "version": 2,
    "title": "Idempotent Operations",
    "phase": "scaling-performance",
    "area": "Scaling & Performance",
    "estimated_minutes": 10,
    "difficulty": "core",
    "summary": "An operation is idempotent if doing it once has the same effect as doing it many times. In distributed systems where retries and duplicates are normal, idempotency is not optional — it's the difference between safe retries and double charges.",
    "why_it_matters": "Networks fail, timeouts happen, messages get redelivered. Without idempotency, every retry risks duplicating side effects — double charges, duplicate emails, inconsistent state. With idempotency, you can retry safely, which is the foundation of every reliable distributed system.",
    "prerequisites": ["rest"],
    "related": ["retry", "message-queues"],
    "used_in": ["Every payment API.", "Every message queue consumer.", "Every retry-safe HTTP client."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "An operation is **idempotent** if calling it once produces the same result as calling it multiple times. Mathematically: `f(f(x)) = f(x)`.\n\n- **Idempotent**: `PUT /users/42 {name: 'Ada'}` — setting a value. Doing it 1 time or 100 times results in the same state.\n- **Not idempotent**: `POST /charges {amount: 100}` — creating a resource. Doing it twice creates two charges.\n\nIn a perfect world, you call an API once and it works. In the real world, networks fail, timeouts happen, and clients retry. If the operation isn't idempotent, retries cause duplicates."}},
        {"type": "diagram", "id": "idempotency", "payload": {"ascii": "  WITHOUT IDEMPOTENCY (dangerous retries)\n  ────────────────────────────────────────\n  Client ──→ POST /charges {amount: $100}\n  Timeout ←──── (network blip)\n  Client retries ──→ POST /charges {amount: $100}\n  Result: TWO charges of $100. User is angry.\n\n  WITH IDEMPOTENCY KEY (safe retries)\n  ────────────────────────────────────\n  Client ──→ POST /charges\n             Headers: Idempotency-Key: abc-123\n             Body: {amount: $100}\n  Timeout ←────\n  Client retries ──→ POST /charges\n                     Idempotency-Key: abc-123\n                     Body: {amount: $100}\n  Server sees key abc-123 already processed\n  → returns the SAME result. No double charge.", "caption": "Idempotency keys make non-idempotent operations safe to retry.", "voice_alt_text": "Two diagrams. Without idempotency: a client sends a POST to charge $100, gets a timeout, retries, and the server creates two charges — the user is double-charged. With an idempotency key: the client sends the same unique key with each request. On retry, the server recognizes the key, skips processing, and returns the original result. No double charge."}},
        {"type": "prose", "id": "http-methods", "payload": {"text": "HTTP methods and idempotency:\n\n- **GET**: idempotent (and safe — no side effects).\n- **PUT**: idempotent — replaces the resource. PUT /users/42 {name:'Ada'} 10 times = same result.\n- **DELETE**: idempotent — deletes the resource. Deleting a non-existent resource returns 404, but the state is the same.\n- **POST**: NOT idempotent — creates a new resource each time.\n- **PATCH**: NOT necessarily idempotent — depends on the operation (PATCH with 'set name to Ada' is idempotent; PATCH with 'increment count by 1' is not).\n\nTo make POST idempotent, use an **idempotency key**: a unique ID sent by the client that the server uses to deduplicate."}},
        {"type": "callout", "id": "idempotency-key", "payload": {"title": "How idempotency keys work", "body": "The client generates a unique key (UUID) for each logical operation and sends it in a header: `Idempotency-Key: 7c8d2f3a-...`. The server stores the key + result. If it sees the same key again, it returns the stored result instead of re-processing. Stripe's API popularized this pattern. It's the standard way to make payments safely retryable.", "kind": "success"}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your payment API receives a POST /charge request, but the network times out. The client retries with the same Idempotency-Key. What should the server do?", "shape": "mcq", "options": ["Process the charge again — the client asked for it.", "Look up the Idempotency-Key. If already processed, return the stored result. If not, process normally.", "Return an error — duplicates are not allowed.", "Charge half the amount since it's a retry."], "answer_index": 1, "rationale": "The server checks if it has seen the Idempotency-Key before. If yes, it returns the stored result (success or failure) without re-processing — this is the whole point of idempotency keys. If the key is new, it processes the charge and stores the result. This makes the operation safe to retry: the client can retry freely without fear of double-charging. Stripe, Square, and Adyen all use this pattern.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "Which HTTP method is NOT idempotent by default?", "shape": "mcq", "options": ["GET", "PUT", "DELETE", "POST"], "answer_index": 3, "rationale": "POST creates a new resource each time it's called. POST /users {name:'Ada'} called 3 times creates 3 users. GET, PUT, and DELETE are idempotent: GET returns the same resource, PUT sets the same state, DELETE removes the resource (and subsequent calls return 404, but the state is the same — resource doesn't exist). To make POST idempotent, use an idempotency key.", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Safe retries — the foundation of reliable distributed systems.", "Handles duplicate messages (at-least-once delivery).", "Prevents double charges, duplicate sends, inconsistent state."], "cons": ["Requires a unique key per logical operation — client must generate and track keys.", "Server must store key→result mapping (storage cost, TTL management).", "Not all operations are naturally idempotent — some require extra work (optimistic locking, conditional updates)."]},
    "failure_modes": ["Idempotency key collision — two different operations get the same key (use UUIDs to prevent).", "Key TTL expires too early — retry after TTL results in duplicate processing.", "Race condition — two requests with the same key arrive simultaneously (use a lock or insert-only table)."],
    "common_mistakes": ["Treating POST as idempotent — it's not; use idempotency keys.", "Forgetting that PATCH is not necessarily idempotent (depends on the operation).", "Not storing the result — if you only check 'have I seen this key?' but don't return the original result, the client gets a different response on retry."],
    "where_you_see_it": ["Every payment API (Stripe, Square, Adyen).", "Every message queue consumer (idempotent processing).", "Every retry-safe HTTP client."],
    "interview_prompts": ["What is idempotency? Why does it matter in distributed systems?", "How do idempotency keys work? When would you use them?", "Which HTTP methods are idempotent? How do you make POST idempotent?"],
    "real_system_mappings": [{"system": "Stripe API", "how": "Accepts Idempotency-Key header on all POST requests. Stores key→result for 24h. Retries with the same key return the original result."}, {"system": "AWS SQS", "how": "Supports deduplication IDs for FIFO queues. If a message with the same dedup ID is sent within 5 minutes, SQS returns the original instead of creating a duplicate."}],
    "status": "published",
})

write_concept('back-pressure', {
    "slug": "back-pressure",
    "version": 2,
    "title": "Back Pressure",
    "phase": "scaling-performance",
    "area": "Scaling & Performance",
    "estimated_minutes": 10,
    "difficulty": "advanced",
    "summary": "Back pressure is when a downstream component signals upstream to slow down because it can't keep up. Without it, a slow consumer causes unbounded queue growth, OOM crashes, and cascading failures. With it, the system degrades gracefully under load.",
    "why_it_matters": "Every system has a bottleneck. Without back pressure, the bottleneck manifests as unbounded memory growth (queues pile up) or unbounded latency (requests pile up). Back pressure is the mechanism that turns 'system crashes under load' into 'system slows down gracefully under load'.",
    "prerequisites": ["horizontal-scaling"],
    "related": ["rate-limiting", "task-queues", "circuit-breaker"],
    "used_in": ["Every system that handles variable load.", "Streaming pipelines.", "Message queue consumers."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "Imagine a water pipe. If the faucet (producer) pours faster than the drain (consumer) can drain, water backs up. In plumbing, this is back pressure. In software, it's the same: if a producer sends faster than a consumer can process, work piles up somewhere.\n\nWithout back pressure, that 'somewhere' is an unbounded queue or an ever-growing connection pool. Eventually, memory runs out and the system crashes. With back pressure, the consumer tells the producer 'slow down' — and the producer does."}},
        {"type": "diagram", "id": "back-pressure", "payload": {"ascii": "  WITHOUT BACK PRESSURE (unbounded queue)\n  ───────────────────────────────────────\n  Producer (10k msg/s) → [ Queue ] → Consumer (5k msg/s)\n                          │\n                          └── grows by 5k msg/s\n                              → OOM in 200 seconds\n\n  WITH BACK PRESSURE (bounded queue)\n  ───────────────────────────────────\n  Producer (10k msg/s) → [ Queue (max 1000) ] → Consumer (5k msg/s)\n                              │\n                              └── when full → 'slow down' signal\n                                  → Producer throttles to 5k msg/s\n                                  → Queue stays bounded\n                                  → System degrades gracefully", "caption": "Without back pressure, queues grow until OOM. With back pressure, the producer slows to match the consumer.", "voice_alt_text": "Two diagrams. Without back pressure: a producer sends 10,000 messages per second, the consumer processes only 5,000. The queue grows by 5,000 messages per second, leading to out-of-memory in 200 seconds. With back pressure: the queue has a maximum size of 1,000. When full, a 'slow down' signal goes to the producer, which throttles to 5,000 messages per second. The queue stays bounded, and the system degrades gracefully."}},
        {"type": "prose", "id": "mechanisms", "payload": {"text": "Back pressure mechanisms:\n\n- **Bounded queues**: queue has a max size. When full, the producer blocks (synchronous) or gets rejected (async).\n- **Reactive streams**: the consumer pulls from the producer (pull-based) rather than the producer pushing. The consumer only requests what it can handle.\n- **HTTP 429 Too Many Requests**: the server tells the client 'slow down'. The client must respect the `Retry-After` header.\n- **TCP flow control**: the OS handles this at the network layer — the receiver advertises a window size, and the sender doesn't exceed it.\n- **Message broker prefetch limits**: the consumer only receives N messages at a time (e.g., Kafka `max.poll.records`, RabbitMQ `prefetch_count`)."}},
        {"type": "callout", "id": "fail-fast", "payload": {"title": "Fail fast, don't pile up", "body": "When a queue is full, you have two choices: block the producer (synchronous back pressure) or reject the request (fail fast). Failing fast is usually better — a 429 error tells the client 'try again later', and the system stays responsive. Blocking causes threads to pile up and cascading failures.", "kind": "note"}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your API has an unbounded in-memory queue for processing requests. Under heavy load, what happens?", "shape": "mcq", "options": ["The system handles the load gracefully.", "The queue grows until memory runs out, causing OOM crashes.", "The system automatically scales up.", "The queue self-cleans old messages."], "answer_index": 1, "rationale": "Without a bound on the queue, incoming requests accumulate faster than they're processed. The queue grows until the process runs out of memory and crashes (OOM). This is why unbounded queues are an anti-pattern in production systems. The fix is to set a maximum queue size and apply back pressure (block or reject) when full. This degrades gracefully (slowdowns or 429s) instead of crashing.", "difficulty": "interview"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "A consumer can process 100 messages per second. The producer sends 200 per second. Which back pressure mechanism prevents the queue from growing unbounded?", "shape": "mcq", "options": ["Unbounded queue — let it grow.", "Bounded queue with rejection — when full, reject new messages (429).", "Add more producers.", "Disable retries."], "answer_index": 1, "rationale": "A bounded queue with rejection is the most common back pressure mechanism. When the queue is full, new messages are rejected (429 Too Many Requests). The producer must slow down or retry later. This keeps the queue bounded and the system responsive. Unbounded queues cause OOM. Adding more producers makes it worse (more input). Disabling retries doesn't solve the throughput mismatch.", "difficulty": "advanced"}}
    ],
    "trade_offs": {"pros": ["Prevents OOM crashes under load — queues stay bounded.", "Graceful degradation — system slows down instead of crashing.", "Protects downstream services from being overwhelmed.", "Natural rate limiting — the consumer's speed sets the system's speed."], "cons": ["Can cause rejected requests (429) — users see errors under load.", "Adds latency — when the queue is near-full, requests wait longer.", "Requires client cooperation — clients must respect 429 and Retry-After.", "Hard to tune — queue size that's too small causes false rejections; too large causes latency."]},
    "failure_modes": ["Unbounded queue — OOM crash under load.", "Queue too large — high latency before back pressure kicks in.", "Client ignores 429 — keeps hammering, causing the queue to stay full.", "Head-of-line blocking — one slow request blocks the whole queue."],
    "common_mistakes": ["Using unbounded queues — always set a max size.", "Blocking instead of rejecting — blocking causes thread exhaustion and cascading failures.", "Not propagating back pressure — if service A applies back pressure to service B, B must propagate it to its callers."],
    "where_you_see_it": ["Every system that handles variable load.", "Streaming pipelines (Kafka, Flink, Reactive Streams).", "Message queue consumers (prefetch limits).", "TCP flow control (window size)."],
    "interview_prompts": ["What is back pressure? Why is it important?", "How do you handle a producer that's faster than the consumer?", "What happens if you use an unbounded queue under load?"],
    "real_system_mappings": [{"system": "Reactive Streams (RxJava, Project Reactor)", "how": "Pull-based back pressure: the consumer requests N items, the producer sends only N. The consumer controls the flow."}, {"system": "Kafka consumer", "how": "prefetch limit (max.poll.records) bounds how many messages the consumer receives at once. If processing is slow, the consumer doesn't poll for more."}],
    "status": "published",
})

write_concept('rate-limiting', {
    "slug": "rate-limiting",
    "version": 2,
    "title": "Rate Limiting",
    "phase": "scaling-performance",
    "area": "Scaling & Performance",
    "estimated_minutes": 12,
    "difficulty": "core",
    "summary": "Rate limiting caps how many requests a client can make in a time window. It protects services from abuse (DDoS, scraping), ensures fair resource sharing, and prevents cascading failures. Common algorithms: token bucket, leaky bucket, fixed window, sliding window.",
    "why_it_matters": "Without rate limiting, a single aggressive client (or a bug in a client's retry loop) can overwhelm your service. Rate limiting is the first line of defense: it protects the service, ensures fair access for all clients, and provides predictable behavior under load. Every public API needs it.",
    "prerequisites": ["back-pressure"],
    "related": ["throttling", "circuit-breaker", "retry"],
    "used_in": ["Every public API.", "Every service that handles untrusted clients.", "Every API gateway."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "Rate limiting caps how many requests a client can make in a time window. Example: '100 requests per minute per API key'. If the client exceeds the limit, the server returns **429 Too Many Requests** with a `Retry-After` header telling the client when to try again.\n\nRate limiting serves three purposes:\n1. **Protection**: prevents abuse (DDoS, scraping, brute force).\n2. **Fairness**: ensures one client can't monopolize resources.\n3. **Cost control**: caps the resources any single client can consume."}},
        {"type": "diagram", "id": "algorithms", "payload": {"ascii": "  TOKEN BUCKET (most common)\n  ─────────────────────────────\n  Bucket holds N tokens (capacity).\n  Refills at R tokens/second.\n  Each request consumes 1 token.\n  If empty → 429.\n\n  Allows bursts up to N, then R/s steady.\n\n\n  LEAKY BUCKET (smooths traffic)\n  ──────────────────────────────\n  Requests enter a queue (bucket).\n  Processed at fixed rate R/s.\n  If queue full → 429.\n\n  Smooths bursts into steady output.\n\n\n  FIXED WINDOW (simple, inaccurate)\n  ────────────────────────────────\n  Count requests per window (e.g., per minute).\n  Reset at window boundary.\n  Problem: 2x burst at window edge.\n\n\n  SLIDING WINDOW (accurate)\n  ──────────────────────────\n  Count requests in the last N seconds.\n  No burst at boundaries.\n  More memory/expensive.", "caption": "Four rate limiting algorithms, each with different burst behavior.", "voice_alt_text": "Four diagrams. Token bucket: a bucket holds N tokens and refills at R per second. Each request consumes a token. If empty, the request is rejected. Allows bursts up to N, then R per second steady. Leaky bucket: requests enter a queue and are processed at a fixed rate. Smooths bursts into steady output. Fixed window: counts requests per minute and resets at the boundary. Problem: 2x burst at the edge. Sliding window: counts requests in the last N seconds. No burst at boundaries, but more expensive."}},
        {"type": "prose", "id": "token-bucket", "payload": {"text": "**Token bucket** is the most common algorithm:\n- The bucket has a **capacity** (max tokens, e.g., 100).\n- Tokens are added at a **refill rate** (e.g., 10/second).\n- Each request consumes 1 token.\n- If the bucket is empty, the request is rejected (429).\n\nThis allows short bursts (up to capacity) while maintaining an average rate (refill rate). It's used by AWS API Gateway, Stripe, and GitHub."}},
        {"type": "prose", "id": "distributed", "payload": {"text": "In a single-server system, rate limiting is easy: an in-memory counter per client. In a distributed system (multiple servers behind a load balancer), you need **shared state** — typically Redis:\n\n- Each server checks/updates the counter in Redis.\n- Redis `INCR` + `EXPIRE` is the standard pattern.\n- This adds 1 Redis round-trip per request (~1ms), which is acceptable.\n- For higher performance, use **sliding window logs** or **sliding window counters** (approximation)."}},
        {"type": "callout", "id": "429", "payload": {"title": "The 429 contract", "body": "When rate limiting, return 429 Too Many Requests with: `Retry-After: 30` (seconds to wait) and a body explaining the limit. Good clients respect this. Bad clients get rate-limited repeatedly. Without the header, clients can't tell how long to wait and may retry immediately — causing more load.", "kind": "note"}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your API allows 100 requests per minute per API key. A client sends 200 requests in the first 10 seconds of the minute. What should happen?", "shape": "mcq", "options": ["All 200 succeed — the client is within the per-minute limit.", "The first 100 succeed; the rest get 429 Too Many Requests with Retry-After.", "All 200 get 429 — the client is too aggressive.", "The API queues the extra 100 for later."], "answer_index": 1, "rationale": "Rate limiting caps the total per window. After 100 requests in the first 10 seconds, the remaining 100 get 429 with a Retry-After header (telling the client to wait 50 seconds for the window to reset). This is the fixed window algorithm. Token bucket would allow the burst if capacity >= 200. The important thing is to return 429 with Retry-After so the client knows when to retry.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "You have 5 API servers behind a load balancer. You need to rate-limit clients at 100 requests/minute globally (not per server). What do you need?", "shape": "mcq", "options": ["In-memory counters on each server.", "A shared counter in Redis (or similar) that all servers check.", "Rate limiting at the load balancer only.", "No rate limiting — let each server handle it."], "answer_index": 1, "rationale": "In-memory counters on each server would allow 100 req/min per server — 500 total, not 100. To enforce 100 globally, all servers must share state. Redis is the standard solution: each server checks and increments the counter in Redis before processing. This adds ~1ms latency per request but ensures accurate global rate limiting. Some load balancers (AWS ALB, Cloudflare) also support rate limiting at the edge, which avoids the Redis dependency.", "difficulty": "interview"}}
    ],
    "trade_offs": {"pros": ["Protects services from abuse and DDoS.", "Ensures fair access for all clients.", "Provides predictable behavior under load.", "Enables business models (free tier: 100 req/min, paid: 10,000)."], "cons": ["Adds latency (Redis round-trip for distributed limiting).", "Can reject legitimate traffic if limits are too aggressive.", "Requires client cooperation (clients must respect 429 and Retry-After).", "Algorithm choice matters — wrong algorithm causes edge-case bursts or false rejections."]},
    "failure_modes": ["Limit too low — legitimate users get rate-limited.", "Limit too high — abuse protection fails.", "Per-server instead of global — 5 servers = 5x the limit.", "No Retry-After header — clients retry immediately, causing more load."],
    "common_mistakes": ["Using in-memory counters in a distributed system (per-server, not global).", "Forgetting the Retry-After header.", "Not differentiating between authenticated and unauthenticated clients (stricter limits for anonymous).", "Rate limiting only by IP (NAT breaks this — many users share one IP)."],
    "where_you_see_it": ["Every public API (GitHub: 5000/hr, Stripe: 100/sec, Twitter: 300/15min).", "API gateways (AWS API Gateway, Kong, Apigee).", "Cloudflare edge rate limiting (DDoS protection)."],
    "interview_prompts": ["What is rate limiting? Why is it important?", "Compare token bucket, leaky bucket, fixed window, and sliding window algorithms.", "How do you implement rate limiting in a distributed system?", "What should the 429 response include?"],
    "real_system_mappings": [{"system": "GitHub API", "how": "Token bucket: 5000 requests/hour for authenticated users. Returns X-RateLimit-Remaining and X-RateLimit-Reset headers."}, {"system": "Cloudflare", "how": "Edge rate limiting at the CDN layer — blocks abusive traffic before it reaches the origin. Configurable per-route limits."}],
    "status": "published",
})

write_concept('sql-vs-nosql', {
    "slug": "sql-vs-nosql",
    "version": 2,
    "title": "SQL vs NoSQL",
    "phase": "databases-data-systems",
    "area": "Databases & Data Systems",
    "estimated_minutes": 13,
    "difficulty": "core",
    "summary": "SQL databases (PostgreSQL, MySQL) store data in tables with strict schemas and support ACID transactions. NoSQL databases (Cassandra, MongoDB, DynamoDB) trade strict consistency for scalability, flexibility, or performance. The choice depends on your data shape, consistency requirements, and scale.",
    "why_it_matters": "Choosing the wrong database is one of the most expensive mistakes in system design. Migrating from SQL to NoSQL (or vice versa) after launch is painful and risky. Understanding when to use each — and when to use both — is a core skill.",
    "prerequisites": ["what-is-system-design"],
    "related": ["key-value-stores", "document-stores", "replication", "sharding"],
    "used_in": ["Almost every production system uses at least one of these."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "The SQL vs NoSQL choice is not about which is 'better' — it's about which trade-offs fit your problem. SQL databases excel at structured data, complex queries, and ACID transactions. NoSQL databases excel at scale, flexible schemas, and specific access patterns.\n\nThe key insight: **NoSQL is not one thing**. It's an umbrella for several different database models — key-value, document, wide-column, graph — each with different trade-offs."}},
        {"type": "diagram", "id": "sql-vs-nosql", "payload": {"ascii": "  SQL (relational)\n  ─────────────────\n  ┌─────────┐  ┌──────────┐  ┌────────┐\n  │ users   │  │ orders   │  │ items  │\n  │─────────│  │──────────│  │────────│\n  │ id (PK) │←─│ user_id  │  │ id     │\n  │ name   │  │ id (PK)  │←─│ order_id│\n  │ email   │  │ total    │  │ name   │\n  └─────────┘  └──────────┘  └────────┘\n\n  Strict schema. JOIN across tables.\n  ACID transactions. Vertical scale.\n\n\n  NoSQL (document store example)\n  ───────────────────────────────\n  ┌──────────────────────────┐\n  │ orders (document)        │\n  │──────────────────────────│\n  │ {                        │\n  │   _id: 'order_42',       │\n  │   user: {                │\n  │     id: 1,               │\n  │     name: 'Ada'          │\n  │   },                     │\n  │   items: [               │\n  │     {name:'Book',qty:1}, │\n  │     {name:'Pen', qty:2}  │\n  │   ],                     │\n  │   total: 45              │\n  │ }                        │\n  └──────────────────────────┘\n\n  Flexible schema. No JOINs.\n  Eventually consistent. Horizontal scale.", "caption": "SQL normalizes data across tables. NoSQL denormalizes into self-contained documents.", "voice_alt_text": "Two diagrams. In SQL, data is normalized across multiple tables — users, orders, items — with primary and foreign keys linking them. JOINs combine data across tables. The schema is strict, transactions are ACID, and scaling is typically vertical. In NoSQL (document store), a single order document contains the user info and items nested inside — a self-contained unit. The schema is flexible, there are no JOINs, consistency is eventual, and scaling is horizontal."}},
        {"type": "prose", "id": "sql-strengths", "payload": {"text": "**SQL strengths:**\n- **ACID transactions**: multi-operation, all-or-nothing. Critical for payments, inventory, bookings.\n- **Structured schema**: columns and types are enforced. Prevents bad data.\n- **JOINs**: query across related tables efficiently.\n- **Mature ecosystem**: ORMs, tooling, decades of optimization.\n- **Consistency**: strong (linearizable) by default.\n\n**SQL weaknesses:**\n- **Vertical scaling**: hard to shard across machines.\n- **Schema changes**: migrations are painful at scale.\n- **Impedance mismatch**: relational model doesn't map cleanly to objects."}},
        {"type": "prose", "id": "nosql-types", "payload": {"text": "**NoSQL types:**\n\n- **Key-value** (Redis, DynamoDB): simplest. Key → value. Extremely fast. No query complexity.\n- **Document** (MongoDB, CouchDB): key → document (JSON). Flexible schema. Good for content, profiles, catalogs.\n- **Wide-column** (Cassandra, HBase): rows with dynamic columns. Good for time-series, high-write throughput.\n- **Graph** (Neo4j): nodes and edges. Good for social networks, recommendation engines, fraud detection.\n\nEach is optimized for a specific access pattern. Choosing the right NoSQL type requires knowing your query patterns."}},
        {"type": "callout", "id": "choose", "payload": {"title": "How to choose", "body": "1. Need ACID transactions (payments, inventory)? → SQL (PostgreSQL).\n2. Need massive write throughput (time-series, logs)? → Wide-column (Cassandra).\n3. Need flexible schema (content, user profiles)? → Document (MongoDB).\n4. Need sub-millisecond reads (cache, counters)? → Key-value (Redis).\n5. Need complex relationships (social graph, recommendations)? → Graph (Neo4j).\n6. Not sure? Start with PostgreSQL. You can migrate later if needed.", "kind": "success"}},
        {"type": "quiz", "id": "q1", "payload": {"question": "You're building a payment system that handles credit card charges. Which database should you use?", "shape": "mcq", "options": ["MongoDB — flexible schema is nice.", "Cassandra — high write throughput.", "PostgreSQL — ACID transactions ensure no double charges.", "Redis — fastest for payment lookups."], "answer_index": 2, "rationale": "Payment systems require ACID transactions: a charge must be all-or-nothing (either the money moves and the record is saved, or neither happens). PostgreSQL (and other SQL databases) guarantee this. NoSQL databases typically sacrifice ACID for availability or scalability — which is fine for social feeds but unacceptable for payments. If the charge and the record don't commit atomically, you get lost charges or double charges. Use PostgreSQL (or another ACID SQL DB) for payments.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "You're building a system that logs 1 billion events per day (time-series data). Which database is best suited?", "shape": "mcq", "options": ["PostgreSQL — it can handle anything.", "Cassandra — optimized for high-write time-series data.", "MongoDB — documents are flexible.", "Neo4j — graph databases handle everything."], "answer_index": 1, "rationale": "Cassandra is a wide-column NoSQL database optimized for exactly this use case: massive write throughput (millions of writes per second) with time-series data. It trades strong consistency for availability and partition tolerance (AP in CAP). PostgreSQL would struggle with 1B writes/day without heavy sharding. MongoDB is better for flexible-schema documents. Neo4j is for graph relationships. For pure write-heavy time-series, Cassandra (or similar wide-column stores like ScyllaDB, HBase) is the right choice.", "difficulty": "interview"}}
    ],
    "trade_offs": {"pros": ["SQL: ACID, JOINs, mature ecosystem, strong consistency.", "NoSQL: horizontal scalability, flexible schema, high throughput for specific patterns.", "NoSQL: each type is optimized for a specific use case (KV=speed, document=flexibility, wide-column=throughput, graph=relationships)."], "cons": ["SQL: hard to shard, schema migrations are painful, vertical scaling ceiling.", "NoSQL: eventual consistency (usually), no JOINs (must denormalize), less mature tooling.", "NoSQL: each type is a specialist — wrong choice = bad performance."]},
    "failure_modes": ["Using NoSQL for transactional data — loses ACID guarantees.", "Using SQL for massive write throughput — can't scale writes without sharding.", "Choosing a NoSQL type without understanding query patterns — e.g., using MongoDB for graph queries.", "Polyglot persistence without clear boundaries — too many databases to maintain."],
    "common_mistakes": ["Treating 'NoSQL' as one thing — it's 4 different models with different trade-offs.", "Choosing NoSQL for 'scalability' without understanding your consistency needs.", "Using SQL when your data is naturally a graph — SQL JOINs for graph queries are slow.", "Forgetting that PostgreSQL can handle JSON (jsonb) — you might not need MongoDB."],
    "where_you_see_it": ["Almost every production system uses at least one SQL or NoSQL database.", "Large systems use both: SQL for transactional data, NoSQL for specific access patterns."],
    "interview_prompts": ["When would you choose SQL over NoSQL?", "What are the different types of NoSQL databases?", "Can you use both SQL and NoSQL in the same system? When?"],
    "real_system_mappings": [{"system": "Uber", "how": "Uses Schemaless (built on MySQL) for most data, Redis for caching, and Cassandra for location tracking. Polyglot persistence."}, {"system": "Netflix", "how": "Uses Cassandra for viewing history (massive writes), EVCache (Redis) for caching, and MySQL for billing (ACID required)."}],
    "status": "published",
})

write_concept('replication', {
    "slug": "replication",
    "version": 2,
    "title": "Replication",
    "phase": "databases-data-systems",
    "area": "Databases & Data Systems",
    "estimated_minutes": 13,
    "difficulty": "core",
    "summary": "Replication copies data from a primary database to one or more replicas. It improves read availability, read throughput, and fault tolerance. The main trade-offs are replication lag (eventual consistency) and write amplification.",
    "why_it_matters": "A single database is a single point of failure. Replication is the standard way to achieve high availability for databases — if the primary dies, a replica takes over. It also enables read scaling: route reads to replicas, writes to the primary.",
    "prerequisites": ["sql-vs-nosql"],
    "related": ["sharding", "cap-theorem", "failover"],
    "used_in": ["Every production database that needs high availability."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "Replication copies data from a **primary** (master) database to one or more **replicas** (slaves). Writes go to the primary; the primary replicates them to replicas. Reads can go to either — but reads from replicas may be stale (eventual consistency).\n\nThis gives you: read scaling (add replicas for more read capacity), high availability (if the primary dies, promote a replica), and geographic distribution (place replicas near users)."}},
        {"type": "diagram", "id": "replication", "payload": {"ascii": "  ┌─────────────────────────────────────┐\n  │              PRIMARY                 │\n  │  (accepts reads + writes)            │\n  └──────────────┬──────────────────────┘\n                 │ replicate (async or sync)\n        ┌────────┼────────┐\n        ▼        ▼        ▼\n  ┌──────────┐ ┌──────────┐ ┌──────────┐\n  │ Replica 1│ │ Replica 2│ │ Replica 3│\n  │ (reads)  │ │ (reads)  │ │ (reads)  │\n  └──────────┘ └──────────┘ └──────────┘\n\n  Writes: always to primary.\n  Reads: primary (strong) or replica (may be stale).\n  Failover: promote a replica if primary dies.", "caption": "Single-primary replication: writes to primary, reads from primary or replicas.", "voice_alt_text": "A diagram of single-primary replication. The primary database accepts both reads and writes. It replicates writes asynchronously or synchronously to three replicas. Writes always go to the primary. Reads can go to the primary (strongly consistent) or to replicas (may be stale due to replication lag). If the primary dies, a replica is promoted to become the new primary."}},
        {"type": "prose", "id": "sync-vs-async", "payload": {"text": "**Synchronous replication**: the primary waits for all (or a quorum of) replicas to acknowledge the write before returning success to the client. Strong consistency, but higher write latency and reduced availability if a replica is down.\n\n**Asynchronous replication**: the primary returns success immediately and replicates in the background. Lower latency, higher availability, but replicas may lag (eventual consistency). If the primary dies before replicating, committed writes can be lost.\n\nMost production systems use **semi-synchronous**: at least one replica acknowledges before the primary returns, but not all. This balances latency, consistency, and availability."}},
        {"type": "callout", "id": "replication-lag", "payload": {"title": "Replication lag", "body": "In async replication, replicas are behind the primary by some amount of time (milliseconds to seconds). This is replication lag. If you read from a replica, you might see stale data. For a social feed, this is fine. For 'did the payment go through?', it's not. Always read from the primary for critical reads.", "kind": "warning"}},
        {"type": "prose", "id": "topologies", "payload": {"text": "Replication topologies:\n\n- **Single-primary** (most common): one primary, N replicas. Simple, but the primary is a write bottleneck.\n- **Multi-primary** (multi-master): any node accepts writes and replicates to others. No write bottleneck, but conflict resolution is complex (last-write-wins, CRDTs, application-level merging).\n- **Chain replication**: A → B → C. Reduces load on the primary but adds latency to the end of the chain.\n- **Star topology**: primary replicates to all replicas directly. Most common."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your system uses async replication with 3 replicas. A user updates their profile, then immediately views it. They see the old profile. Why?", "shape": "mcq", "options": ["The database lost the write.", "The read went to a replica that hasn't received the update yet (replication lag).", "The user's browser cached the old page.", "The primary rejected the write."], "answer_index": 1, "rationale": "In async replication, the primary returns success immediately, then replicates in the background. If the subsequent read goes to a replica, the replica may not have received the update yet — this is replication lag. The write wasn't lost; it just hasn't propagated. The fix: for read-after-write consistency, either read from the primary, or use read-your-writes consistency (route the user's reads to the primary for a short window after their write).", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "Your primary database dies. You have 3 async replicas. What must happen for the system to recover?", "shape": "mcq", "options": ["Nothing — the replicas are already up to date.", "Promote one replica to primary. Some recent writes may be lost (those not yet replicated).", "All replicas become primaries simultaneously.", "The system is down until the primary is restored."], "answer_index": 1, "rationale": "In async replication, a promoted replica may not have the latest writes — those that were committed on the primary but not yet replicated. This is the fundamental trade-off of async replication: lower latency but potential data loss on failover. The fix is semi-synchronous replication (at least one replica has the write before the primary acknowledges), which reduces but doesn't eliminate the window. After promotion, the system must also update routing (load balancer, connection strings) to point to the new primary.", "difficulty": "interview"}}
    ],
    "trade_offs": {"pros": ["High availability — survive primary failure.", "Read scaling — add replicas for more read capacity.", "Geographic distribution — replicas near users reduce latency.", "Backup — replicas can serve as live backups."], "cons": ["Replication lag — async replicas are eventually consistent.", "Write amplification — each write is replicated N times.", "Failover complexity — promoting a replica, updating routing.", "Cost — more machines, more storage."]},
    "failure_modes": ["Replication lag — stale reads from replicas.", "Split-brain — network partition causes two primaries, divergent writes.", "Write bottleneck — single primary can't handle write throughput.", "Data loss on failover — async replication means the last few writes may not be on any replica."],
    "common_mistakes": ["Reading from replicas for critical data (payments, permissions).", "Using async replication when you need zero data loss on failover.", "Forgetting to test failover — it works in theory but breaks in practice.", "Not monitoring replication lag — a lagging replica is a time bomb."],
    "where_you_see_it": ["Every production database that needs high availability.", "Every read-heavy system.", "Every geographically distributed system."],
    "interview_prompts": ["What is database replication? What are the trade-offs between sync and async?", "How do you handle replication lag?", "What happens when the primary fails? How do you promote a replica?"],
    "real_system_mappings": [{"system": "PostgreSQL streaming replication", "how": "Async by default, sync available. Replicas can be read-only (hot standby) or take over (promoted)."}, {"system": "MySQL Group Replication", "how": "Multi-primary with conflict detection. Uses Paxos-like consensus for write agreement."}],
    "status": "published",
})

write_concept('sharding', {
    "slug": "sharding",
    "version": 2,
    "title": "Sharding",
    "phase": "databases-data-systems",
    "area": "Databases & Data Systems",
    "estimated_minutes": 14,
    "difficulty": "advanced",
    "summary": "Sharding splits a database into smaller pieces (shards) distributed across multiple machines. Each shard holds a subset of the data. This enables horizontal scaling of both reads and writes — but adds complexity in routing, cross-shard queries, and rebalancing.",
    "why_it_matters": "Replication gives you read scaling, but writes still go to one primary. When the primary can't keep up, sharding is the answer: split the data so writes are distributed across multiple primaries. This is how every large-scale database (Facebook, Uber, Netflix) handles write throughput.",
    "prerequisites": ["replication", "consistent-hashing"],
    "related": ["federation", "cap-theorem"],
    "used_in": ["Every large-scale database.", "Every system with write throughput beyond a single machine."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "Sharding (also called horizontal partitioning) splits a large table into smaller pieces, each on a different machine. Example: users table split by user_id — shard 1 holds users 1-1M, shard 2 holds 1M-2M, etc. Each shard is an independent database.\n\nThis enables horizontal scaling of **writes** (each shard handles its own writes) and **reads** (each shard handles its own reads). The trade-off: cross-shard queries (e.g., 'count all users') require querying every shard and aggregating."}},
        {"type": "diagram", "id": "sharding", "payload": {"ascii": "  WITHOUT SHARDING (single primary)\n  ─────────────────────────────────\n  All writes → [ Primary DB ] → All reads\n  Ceiling: one machine's write capacity.\n\n  WITH SHARDING (multiple primaries)\n  ────────────────────────────────────\n  Write request → [ Shard Router ]\n                      │\n           ┌──────────┼──────────┐\n           ▼          ▼          ▼\n       [Shard 1]  [Shard 2]  [Shard 3]\n       users 1-1M  1M-2M     2M-3M\n           │          │          │\n           ▼          ▼          ▼\n       [Repl 1]  [Repl 2]  [Repl 3]\n\n  Each shard: own primary + replicas.\n  Writes scale: 3x throughput.\n  Reads scale: 3x throughput.", "caption": "Sharding distributes data across multiple databases, scaling both reads and writes.", "voice_alt_text": "Two diagrams. Without sharding: all writes go to one primary database, which has a ceiling at one machine's write capacity. With sharding: a shard router distributes write requests across three shards, each holding a subset of users. Each shard has its own primary and replicas. Both writes and reads scale by 3x."}},
        {"type": "prose", "id": "shard-key", "payload": {"text": "The **shard key** (partition key) determines which shard holds a row. Choosing the right shard key is the most important sharding decision:\n\n- **Good**: `user_id` — distributes evenly, enables per-user queries on a single shard.\n- **Bad**: `timestamp` — all writes go to the latest shard (hot spot).\n- **Bad**: `country` — uneven distribution (US has more users than NZ).\n- **Bad**: `last_name` — uneven distribution (more Smiths than Zywickis).\n\nThe shard key must distribute data evenly AND enable common queries without cross-shard fan-out."}},
        {"type": "callout", "id": "consistent-hashing", "payload": {"title": "Consistent hashing", "body": "Adding or removing a shard is expensive if you use fixed ranges (you have to move data). Consistent hashing minimizes data movement: each shard owns a range on a hash ring, and adding a shard only moves the keys in the new shard's range. See the Consistent Hashing lesson.", "kind": "note"}},
        {"type": "prose", "id": "challenges", "payload": {"text": "Sharding introduces hard problems:\n\n- **Cross-shard queries**: 'count all users' queries every shard and sums. Slow and expensive.\n- **Joins**: joining data across shards is hard. Usually denormalize to avoid it.\n- **Transactions**: a transaction spanning two shards requires distributed transactions (2PC) — slow and complex. Avoid by keeping transactions within a shard.\n- **Rebalancing**: when a shard gets too big, you need to split it — moving data and updating the router. Online rebalancing is hard.\n- **Hot shards**: if the shard key is uneven, one shard gets most traffic. Reshard.\n\nThese challenges are why sharding is a last resort — try replication, caching, and read replicas first."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "You're sharding a users table. Which shard key is the BEST choice?", "shape": "mcq", "options": ["timestamp — newest users go to the latest shard.", "country — group users by location.", "user_id (hashed) — distributes evenly and enables per-user lookups.", "last_name — alphabetical grouping."], "answer_index": 2, "rationale": "A hashed user_id is the best shard key: it distributes data evenly (no hot spots), enables per-user queries on a single shard (look up the shard from the hash), and doesn't create skew. timestamp creates a hot shard (all writes go to the latest shard). country creates uneven distribution (US has more users). last_name is uneven (more Smiths). The ideal shard key distributes evenly AND supports common query patterns without cross-shard fan-out.", "difficulty": "interview"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "Your sharded database has 5 shards. A user wants to see their order history. How many shards do you query?", "shape": "mcq", "options": ["All 5 — you don't know which shard has their data.", "1 — if orders are sharded by user_id, only one shard has this user's orders.", "2 — the shard with the data plus a replica.", "0 — sharded databases can't do this."], "answer_index": 1, "rationale": "If orders are sharded by user_id, the shard router computes hash(user_id) and routes the query to exactly one shard. This is the key benefit of good shard key design: per-entity queries hit only one shard. The query is fast (one shard, not five) and doesn't require cross-shard coordination. The trade-off: queries that span users (e.g., 'total orders across all users') require querying all 5 shards and aggregating.", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Scales both reads AND writes (unlike replication, which only scales reads).", "Each shard is independent — no distributed writes for per-shard operations.", "Enables databases beyond a single machine's capacity."], "cons": ["Cross-shard queries are expensive (fan-out + aggregate).", "Cross-shard transactions require 2PC (slow, complex).", "Rebalancing is hard (adding/removing shards moves data).", "Choosing the wrong shard key is catastrophic (hot spots, uneven distribution).", "Operational complexity — backup, monitor, and migrate N databases."]},
    "failure_modes": ["Hot shard — bad shard key causes uneven distribution.", "Cross-shard transactions — slow and can deadlock.", "Rebalancing — moving data between shards is expensive and risky.", "Shard key change — if you need to re-shard, it's a massive migration."],
    "common_mistakes": ["Sharding too early — try replication, caching, and read replicas first.", "Choosing a shard key that creates hot spots (timestamp, auto-increment).", "Forgetting that cross-shard queries are expensive — design queries to be shard-local.", "Not planning for rebalancing — what happens when a shard grows too big?"],
    "where_you_see_it": ["Every large-scale database (Facebook, Uber, Netflix).", "Every system with write throughput beyond a single machine.", "Cassandra, MongoDB, DynamoDB (built-in sharding)."],
    "interview_prompts": ["What is sharding? When would you shard a database?", "How do you choose a shard key?", "What are the challenges of sharding?", "Sharding vs replication — how do they differ?"],
    "real_system_mappings": [{"system": "Uber", "how": "Sharded Schemaless (their custom DB on top of MySQL) by UUID. Each shard is a MySQL primary + replicas. Tens of thousands of shards."}, {"system": "Cassandra", "how": "Sharding is built-in. Uses consistent hashing to distribute data across nodes. Each node owns a range of the hash ring."}],
    "status": "published",
})

print("\n✅ Remaining priority concepts written")
