#!/usr/bin/env python3
"""Generate deep content for Async + remaining priority concepts."""
import json, os
CONCEPTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'content', 'concepts')

def write_concept(slug, data):
    fpath = os.path.join(CONCEPTS_DIR, f'{slug}.json')
    with open(fpath, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write('\n')
    print(f'  Wrote {slug} ({len(data.get("blocks",[]))} blocks)')

write_concept('message-queues', {
    "slug": "message-queues",
    "version": 2,
    "title": "Message Queues",
    "phase": "scaling-performance",
    "area": "Scaling & Performance",
    "estimated_minutes": 13,
    "difficulty": "core",
    "summary": "A message queue decouples producers from consumers. Producers write messages to a queue; consumers read them at their own pace. This smooths traffic spikes, enables async processing, and lets producers and consumers scale independently.",
    "why_it_matters": "Without a queue, a traffic spike to your service causes it to synchronously call downstream services, which also spike, which cascade into failure. A queue absorbs the spike — producers write quickly and move on, consumers process at a steady rate. This is the single most important pattern for building resilient, scalable backends.",
    "prerequisites": ["task-queues"],
    "related": ["pub-sub", "event-driven-architecture", "competing-consumers", "back-pressure"],
    "used_in": ["Every async backend.", "Every event-driven system.", "Every system that handles traffic spikes."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "A message queue is a buffer between producers and consumers. Producers write messages to the queue; consumers read them asynchronously. The key insight: **the producer doesn't wait for the consumer to process the message** — it writes and moves on.\n\nThis decoupling has three benefits:\n1. **Smoothing**: if producers burst, the queue absorbs the spike and consumers process at a steady rate.\n2. **Decoupling**: producers and consumers can scale independently.\n3. **Reliability**: if a consumer crashes, messages stay in the queue (or are redelivered) — no data loss."}},
        {"type": "diagram", "id": "queue-flow", "payload": {"ascii": "  Producer 1 ──┐\n  Producer 2 ──┼──→ [ MESSAGE QUEUE ] ──→ Consumer 1\n  Producer 3 ──┘         │               ──→ Consumer 2\n                          │               ──→ Consumer 3\n                          v\n                    (FIFO: first in,\n                     first out)\n\n  Producers write fast.    Consumers read at their own pace.\n  Queue absorbs the spike.  Add more consumers to scale.", "caption": "A message queue decouples producers from consumers, smoothing traffic spikes.", "voice_alt_text": "A diagram of a message queue. Multiple producers write messages into a queue, which acts as a FIFO buffer. Multiple consumers read from the queue at their own pace. Producers can write fast while consumers process at a steady rate. The queue absorbs traffic spikes. Add more consumers to scale throughput."}},
        {"type": "prose", "id": "delivery", "payload": {"text": "Message delivery semantics:\n\n- **At-most-once**: messages may be lost but never duplicated. Simple, fast, unreliable.\n- **At-least-once**: messages are never lost but may be duplicated. Requires idempotent consumers. Most common.\n- **Exactly-once**: messages are delivered once and only once. Expensive to achieve (requires distributed consensus). Often simulated with at-least-once + idempotency.\n\nMost systems use at-least-once + idempotency. This is why **idempotent operations** (the previous lesson) are so important — they make at-least-once delivery safe."}},
        {"type": "callout", "id": "exactly-once-myth", "payload": {"title": "The exactly-once myth", "body": "True exactly-once delivery across a distributed system is impossible without giving up availability (FLP impossibility). What systems like Kafka call 'exactly-once' is actually at-least-once + transactional idempotency — the consumer deduplicates using a message ID. This is good enough for almost all use cases.", "kind": "warning"}},
        {"type": "prose", "id": "patterns", "payload": {"text": "Common queue patterns:\n\n- **Work queue**: one queue, multiple consumers (competing consumers). Each message is processed by exactly one consumer. Used for background jobs (send email, process image).\n- **Pub/sub**: one message, multiple subscribers. Each subscriber gets a copy. Used for event notifications.\n- **Request-response**: the producer sends a message and waits for a reply (via a reply queue). Used for async RPC.\n- **Dead-letter queue**: messages that fail processing N times are moved to a DLQ for inspection. Prevents poison messages from blocking the queue."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your e-commerce site has a flash sale. Traffic spikes 100x for 2 minutes. Without a message queue, what happens?", "shape": "mcq", "options": ["The site handles it fine — servers are elastic.", "The order processing service is overwhelmed, timeouts cascade, and the site goes down.", "The database handles the spike automatically.", "Users see faster responses because of caching."], "answer_index": 1, "rationale": "Without a queue, every order request synchronously calls the order processing service. A 100x spike means 100x concurrent calls, which overwhelms the service — timeouts pile up, connections exhaust, and the site goes down. With a queue, the web servers write order messages quickly (1ms) and move on. The order processing service reads from the queue at a steady rate it can handle. The spike is absorbed, and orders process within seconds instead of failing.", "difficulty": "interview"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "A message queue delivers messages at-least-once. Your consumer processes a 'charge credit card' message. What must you do?", "shape": "mcq", "options": ["Nothing — at-least-once means it's safe.", "Make the consumer idempotent: use an idempotency key so duplicate messages don't cause double charges.", "Switch to exactly-once delivery.", "Process each message only once."], "answer_index": 1, "rationale": "At-least-once means the same message may be delivered multiple times (due to consumer crashes, network retries, etc.). If your consumer charges a credit card, a duplicate delivery would double-charge. The solution is idempotency: include a unique message ID, and before charging, check if you've already processed that ID. If yes, skip. This makes at-least-once delivery safe. True exactly-once is impractical in distributed systems — idempotency is the standard solution.", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Smooths traffic spikes — producers write fast, consumers process steadily.", "Decouples producers from consumers — they scale independently.", "Reliable — messages persist in the queue even if consumers crash.", "Enables async processing — producers don't block on slow operations."], "cons": ["Adds latency — messages are processed asynchronously, not immediately.", "Adds infrastructure — another system to deploy, monitor, and debug.", "Requires idempotent consumers — duplicate delivery is normal.", "Operational complexity — dead-letter queues, retries, ordering guarantees."]},
    "failure_modes": ["Poison messages — a message that always fails processing blocks the queue (mitigated by DLQ + max retries).", "Queue buildup — consumers can't keep up; queue grows unbounded (mitigated by back-pressure + auto-scaling).", "Message ordering — in distributed queues, FIFO is expensive and often not guaranteed across partitions.", "Consumer crash mid-processing — message may be redelivered (mitigated by idempotency)."],
    "common_mistakes": ["Assuming exactly-once delivery — it's almost always at-least-once.", "Not handling duplicate messages — every consumer must be idempotent.", "Using a queue when a synchronous call would do — adds unnecessary complexity.", "Forgetting to monitor queue depth — a growing queue is the first sign of trouble."],
    "where_you_see_it": ["Every async backend (email, notifications, image processing).", "Every event-driven microservice architecture.", "Every system that handles traffic spikes (flash sales, viral content)."],
    "interview_prompts": ["What is a message queue? How does it differ from a pub/sub system?", "What are the delivery semantics? Why is exactly-once hard?", "How do you handle duplicate messages in a consumer?", "When would you use a queue vs a synchronous call?"],
    "real_system_mappings": [{"system": "RabbitMQ", "how": "Classic message broker with rich routing, acknowledgments, and dead-letter exchanges. At-least-once delivery with optional transactions."}, {"system": "AWS SQS", "how": "Managed message queue with at-least-once delivery, dead-letter queues, and visibility timeouts. Standard (unordered, at-least-once) and FIFO (ordered, exactly-once via dedup ID) modes."}],
    "status": "published",
})

write_concept('event-driven-architecture', {
    "slug": "event-driven-architecture",
    "version": 2,
    "title": "Event-Driven Architecture",
    "phase": "asynchronous-systems",
    "area": "Asynchronous Systems",
    "estimated_minutes": 12,
    "difficulty": "advanced",
    "summary": "Event-driven architecture (EDA) is a pattern where services communicate by producing and consuming events, rather than calling each other directly. Producers emit events ('user created', 'order placed') without knowing who consumes them. This enables loose coupling, easy extensibility, and independent scaling.",
    "why_it_matters": "In a request-response architecture, every service must know the address of every service it calls. Add a new consumer (e.g., analytics) and you must modify the producer. In EDA, the producer just emits 'user created' — any service that cares subscribes. This is how Netflix, Uber, and LinkedIn scale to hundreds of services without coupling hell.",
    "prerequisites": ["message-queues-async"],
    "related": ["pub-sub", "message-queues", "competing-consumers"],
    "used_in": ["Every modern microservice architecture.", "Every system with many independent consumers."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "In a traditional request-response architecture, service A calls service B: `POST /users {name: 'Ada'}`. B processes and returns. If you later add an analytics service that also needs to know about new users, you must modify A to also call analytics.\n\nIn event-driven architecture, A emits an event: `event: UserCreated {id: 42, name: 'Ada'}`. A message broker routes it to any subscriber. Analytics, email, audit, and recommendation services all subscribe independently — A doesn't know or care who consumes the event."}},
        {"type": "diagram", "id": "eda-vs-request", "payload": {"ascii": "  REQUEST-RESPONSE (tightly coupled)\n  ──────────────────────────────────\n  [User Service] ──→ [Email Service]\n                ──→ [Analytics]\n                ──→ [Recommendation]\n  Adding a new consumer = modifying the producer.\n\n\n  EVENT-DRIVEN (loosely coupled)\n  ────────────────────────────────\n  [User Service] ──→ [Event: UserCreated]\n                          │\n                ┌─────────┼─────────┐\n                v         v         v\n          [Email]   [Analytics]  [Recommendation]\n\n  Adding a new consumer = subscribe to the event.\n  Producer is unchanged.", "caption": "EDA decouples producers from consumers. New consumers don't require producer changes.", "voice_alt_text": "Two diagrams. In request-response, the user service directly calls email, analytics, and recommendation services. Adding a new consumer means modifying the producer. In event-driven architecture, the user service emits a UserCreated event to a broker, which routes it to all subscribers. Adding a new consumer just means subscribing — the producer is unchanged."}},
        {"type": "prose", "id": "events-vs-commands", "payload": {"text": "There are two types of messages in EDA:\n\n- **Events** (facts): 'UserCreated', 'OrderPlaced'. Past tense, immutable. The producer doesn't expect a response. Multiple consumers can react independently.\n- **Commands** (requests): 'SendEmail', 'ChargeCard'. Imperative, directed. The producer expects something to happen. Usually one consumer.\n\nEvents enable true decoupling. Commands are closer to RPC over a queue. Most systems use both: events for broadcasting facts, commands for requesting specific actions."}},
        {"type": "callout", "id": "eventual-consistency", "payload": {"title": "Embrace eventual consistency", "body": "EDA is inherently eventually consistent. When you emit 'UserCreated', the email service might process it 100ms later. During that window, the user exists but hasn't received a welcome email. This is usually fine — but if your UX requires immediate consistency (e.g., 'you can't proceed until the email is sent'), EDA is the wrong choice.", "kind": "warning"}},
        {"type": "prose", "id": "benefits", "payload": {"text": "Benefits of EDA:\n\n- **Loose coupling**: producers don't know consumers. Add/remove consumers without touching producers.\n- **Independent scaling**: each consumer scales independently based on its own load.\n- **Resilience**: if a consumer is down, events queue up (or are redelivered) — no data loss.\n- **Extensibility**: add a new consumer (e.g., ML training pipeline) without modifying any existing service.\n- **Audit trail**: events form an immutable log of what happened in the system.\n\nThe trade-off: eventual consistency, harder debugging (no single call stack), and the need for event schema management."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your e-commerce system currently calls the email service synchronously when an order is placed. You want to add an analytics service that also needs to know about orders. What's the event-driven approach?", "shape": "mcq", "options": ["Modify the order service to also call the analytics service synchronously.", "Have the order service emit an 'OrderPlaced' event. Both email and analytics subscribe to it. The order service doesn't change.", "Have analytics poll the order database every minute.", "Create a new API endpoint that both email and analytics call."], "answer_index": 1, "rationale": "In event-driven architecture, the order service emits an 'OrderPlaced' event to a broker. Email and analytics both subscribe independently. Adding analytics doesn't require any changes to the order service — it just subscribes to the event. This is the core benefit of EDA: loose coupling. The producer doesn't know or care who consumes its events. Options 1 and 4 require modifying the producer; option 3 is polling, which is inefficient and adds latency.", "difficulty": "interview"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "What is the difference between an event and a command in EDA?", "shape": "mcq", "options": ["They are the same thing.", "An event is a fact that happened (past tense, broadcast to many). A command is a request to do something (imperative, directed to one consumer).", "Events are faster than commands.", "Commands are more reliable than events."], "answer_index": 1, "rationale": "Events are facts: 'UserCreated', 'OrderPlaced'. They're past tense, immutable, and broadcast to any subscriber. The producer doesn't expect a response. Commands are requests: 'SendEmail', 'ChargeCard'. They're imperative, directed at a specific consumer, and the producer expects something to happen. Events enable true decoupling (many independent consumers); commands are closer to RPC over a queue. Most systems use both.", "difficulty": "advanced"}}
    ],
    "trade_offs": {"pros": ["Loose coupling — add/remove consumers without touching producers.", "Independent scaling — each consumer scales on its own.", "Resilience — consumers can be down without losing events.", "Extensibility — new consumers subscribe without code changes.", "Audit trail — events form an immutable log."], "cons": ["Eventual consistency — consumers process asynchronously, not immediately.", "Harder debugging — no single call stack; distributed tracing needed.", "Event schema evolution — changing event structure breaks consumers.", "Infrastructure complexity — message broker, event registry, schema management."]},
    "failure_modes": ["Event schema changes break consumers — use schema registry and versioning.", "Consumer falls behind — queue grows, events are delayed (mitigated by auto-scaling + alerting).", "Duplicate events — consumers must be idempotent (at-least-once delivery).", "Circular event chains — service A emits event, B consumes and emits another, which causes A to emit again... (mitigated by careful event design)."],
    "common_mistakes": ["Treating events as commands — expecting a response or directing them at a specific consumer.", "Not versioning event schemas — a field rename breaks all consumers.", "Making events too granular — 'UserFieldUpdated' for every field change floods the system.", "Forgetting eventual consistency — assuming all consumers have processed the event immediately."],
    "where_you_see_it": ["Every modern microservice architecture (Netflix, Uber, LinkedIn).", "Every system with many independent consumers of the same data.", "Every system that needs an audit trail."],
    "interview_prompts": ["What is event-driven architecture? How does it differ from request-response?", "What's the difference between an event and a command?", "How do you handle event schema evolution?", "When would you NOT use EDA?"],
    "real_system_mappings": [{"system": "Netflix", "how": "Hundreds of microservices communicate via events on Kafka. The 'user played a movie' event triggers recommendations, billing, and analytics — all independently."}, {"system": "Uber", "how": "Domain events (trip requested, driver assigned, trip completed) flow through Kafka to dozens of consuming services. Each domain owns its events."}],
    "status": "published",
})

write_concept('pub-sub', {
    "slug": "pub-sub",
    "version": 2,
    "title": "Publish/Subscribe (Pub/Sub)",
    "phase": "asynchronous-systems",
    "area": "Asynchronous Systems",
    "estimated_minutes": 11,
    "difficulty": "advanced",
    "summary": "Pub/sub is a messaging pattern where producers (publishers) send messages to topics, and consumers (subscribers) receive messages from topics they subscribe to. Unlike a work queue (where each message goes to one consumer), pub/sub delivers each message to ALL subscribers.",
    "why_it_matters": "Pub/sub is the foundation of event-driven architecture. It enables broadcasting events to multiple independent consumers without the producer knowing who they are. Every notification system, every event-driven microservice, and every real-time data pipeline uses pub/sub.",
    "prerequisites": ["event-driven-architecture"],
    "related": ["message-queues", "competing-consumers"],
    "used_in": ["Notification systems.", "Event-driven microservices.", "Real-time data pipelines."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "In pub/sub:\n\n- **Publishers** send messages to a **topic** (a named channel).\n- **Subscribers** express interest in one or more topics.\n- The **broker** delivers each message to ALL subscribers of that topic.\n\nThis is fundamentally different from a work queue, where each message goes to exactly ONE consumer. In pub/sub, every subscriber gets a copy."}},
        {"type": "diagram", "id": "pubsub-vs-queue", "payload": {"ascii": "  WORK QUEUE (each message → one consumer)\n  ─────────────────────────────────────────\n  Producer → [ Queue ] → Consumer A (gets msg 1)\n                        → Consumer B (gets msg 2)\n                        → Consumer C (gets msg 3)\n  Messages are distributed across consumers.\n\n  PUB/SUB (each message → ALL subscribers)\n  ────────────────────────────────────────\n  Producer → [ Topic ] → Subscriber A (gets msg 1, 2, 3)\n                        → Subscriber B (gets msg 1, 2, 3)\n                        → Subscriber C (gets msg 1, 2, 3)\n  Each subscriber gets a copy of every message.", "caption": "Work queue: one consumer per message. Pub/sub: all subscribers get each message.", "voice_alt_text": "Two diagrams. In a work queue, a producer sends messages to a queue, and each message goes to exactly one consumer — messages are distributed across consumers. In pub/sub, a producer sends messages to a topic, and every subscriber gets a copy of every message. The key difference: work queue distributes work, pub/sub broadcasts events."}},
        {"type": "prose", "id": "use-cases", "payload": {"text": "Pub/sub is used when:\n\n- **Multiple independent consumers** need the same event. Example: 'UserCreated' event → email service sends welcome, analytics records signup, recommendation service initializes profile.\n- **Consumers have different processing speeds**. The broker buffers per-subscriber.\n- **New consumers can be added dynamically** without modifying the publisher.\n\nWork queues are used when:\n- **Each message should be processed once**. Example: 'send email' — only one service should send it.\n- **You want to parallelize work** across multiple workers.\n- **The order of processing matters less than throughput**."}},
        {"type": "callout", "id": "fanout", "payload": {"title": "Fan-out", "body": "Pub/sub is a 'fan-out' pattern: one input, many outputs. The broker duplicates each message to every subscriber. This means total throughput scales with the number of subscribers — if you have 10 subscribers, the broker handles 10x the message volume. This is why pub/sub brokers (Kafka, Pulsar) are designed for massive throughput.", "kind": "note"}},
        {"type": "prose", "id": "delivery", "payload": {"text": "Pub/sub delivery guarantees vary by broker:\n\n- **At-most-once**: fire-and-forget. Fast, but messages can be lost. Used for metrics/telemetry.\n- **At-least-once**: messages are redelivered if not acknowledged. Most common. Requires idempotent subscribers.\n- **Exactly-once**: rare and expensive. Usually simulated with idempotency keys + transactional consumers.\n\nMost pub/sub systems (Kafka, Google Pub/Sub, SNS) offer at-least-once by default. Subscribers must handle duplicates."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "You have 3 services that all need to know when a user signs up: email (send welcome), analytics (record signup), and recommendations (init profile). Which messaging pattern should you use?", "shape": "mcq", "options": ["Work queue — distribute the signup across the 3 services.", "Pub/sub — each service subscribes to the 'UserCreated' topic and gets a copy.", "Direct HTTP calls from the signup service to each of the 3 services.", "Polling — each service polls the user database every minute."], "answer_index": 1, "rationale": "All 3 services need the same event (user signup), but they process it independently. This is the textbook use case for pub/sub: each service subscribes to the 'UserCreated' topic and gets a copy of every signup event. The publisher (signup service) doesn't know or care who the subscribers are. A work queue would send each signup to only ONE service — wrong. Direct HTTP calls couple the signup service to all consumers, making it hard to add/remove services. Polling is inefficient.", "difficulty": "interview"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "What is 'fan-out' in the context of pub/sub?", "shape": "mcq", "options": ["The publisher sends messages to multiple topics.", "Each message is duplicated and delivered to all subscribers of a topic.", "Subscribers can subscribe to multiple topics.", "The broker scales horizontally."], "answer_index": 1, "rationale": "Fan-out means the broker takes one message and delivers a copy to every subscriber. If a topic has 10 subscribers, each message is duplicated 10 times. This is the defining characteristic of pub/sub: one input, many outputs. The publisher sends once; the broker fans out to all subscribers.", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Broadcasts events to all subscribers — one publish, many consumes.", "Decouples publishers from subscribers — add/remove subscribers without code changes.", "Each subscriber processes at its own pace — independent scaling.", "Enables event-driven architecture."], "cons": ["Every subscriber gets every message — wasteful if subscribers only care about a subset (use filtering).", "Higher throughput requirements — broker handles N copies per message.", "Ordering across subscribers is not guaranteed — each subscriber may process at different speeds.", "Harder to debug — no single call stack; distributed tracing needed."]},
    "failure_modes": ["Slow subscriber backs up the broker — use per-subscriber queues (Kafka consumer groups, SNS+SQS).", "Duplicate delivery — subscribers must be idempotent.", "Message ordering — within a partition, usually FIFO; across partitions, not guaranteed.", "Schema changes break subscribers — use schema registry and versioning."],
    "common_mistakes": ["Using pub/sub when only one consumer needs each message (use a work queue instead).", "Forgetting that delivery is at-least-once — subscribers must handle duplicates.", "Not filtering — if a subscriber only cares about 'high-priority' events, use topic filtering instead of consuming everything.", "Assuming global ordering — pub/sub usually only guarantees per-partition ordering."],
    "where_you_see_it": ["Notification systems (AWS SNS → SQS, Google Pub/Sub).", "Event-driven microservices (Kafka topics with multiple consumer groups).", "Real-time data pipelines (Kafka → Spark, Flink, Cassandra)."],
    "interview_prompts": ["What is the difference between pub/sub and a message queue?", "When would you choose pub/sub over a work queue?", "How do you handle slow subscribers in a pub/sub system?", "What delivery guarantees does pub/sub typically provide?"],
    "real_system_mappings": [{"system": "AWS SNS + SQS", "how": "SNS is the pub/sub topic; SQS queues subscribe to it. Each SQS queue is per-consumer, so a slow consumer doesn't block others. This is the standard AWS pattern for fan-out."}, {"system": "Apache Kafka", "how": "Topics with multiple consumer groups. Each group gets a copy of every message (pub/sub). Within a group, messages are distributed across consumers (work queue). This dual mode makes Kafka versatile."}],
    "status": "published",
})

print("\n✅ Async concepts written")
