#!/usr/bin/env python3
"""
Generate deep, high-quality content for priority concepts.
Each concept gets the full 14-point structure:
  summary, why_it_matters, blocks (prose+diagram+code+quiz), trade_offs,
  failure_modes, common_mistakes, where_you_see_it, interview_prompts,
  real_system_mappings, prerequisites, related, status='published'
"""
import json, os

CONCEPTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'content', 'concepts')

def write_concept(slug, data):
    fpath = os.path.join(CONCEPTS_DIR, f'{slug}.json')
    with open(fpath, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write('\n')
    print(f'  Wrote {slug} ({len(data.get("blocks",[]))} blocks, {sum(1 for b in data.get("blocks",[]) if b.get("type")=="quiz")} quizzes)')

# ─────────────────────────────────────────────────────────────────────
# FOUNDATIONS
# ─────────────────────────────────────────────────────────────────────

write_concept('what-is-system-design', {
    "slug": "what-is-system-design",
    "version": 2,
    "title": "What is System Design",
    "phase": "foundations",
    "area": "Foundations",
    "estimated_minutes": 8,
    "difficulty": "core",
    "summary": "System design is the process of defining the architecture, components, and interfaces of a software system to meet specific requirements around scalability, reliability, performance, and maintainability. It is the bridge between 'code that works' and 'systems that survive production.'",
    "why_it_matters": "Most code works on your laptop. Most systems fail in production — under real load, with real failures, with real users who do unexpected things. System design is the discipline that prevents those failures. Every interview, every architecture review, every incident postmortem is fundamentally a system-design conversation.",
    "prerequisites": [],
    "related": ["how-to-approach-system-design", "performance-vs-scalability"],
    "used_in": ["Every production software system ever built."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "System design answers a deceptively simple question: **how do you build software that works at scale, survives failures, and can be maintained over time?** The question is simple because the goal is obvious. The answer is hard because 'scale', 'failure', and 'time' each pull in different directions.\n\nWhen you write a script that reads a file and prints the result, you are programming. When you ask 'what happens if 10,000 people run this script at the same time, on different machines, and one of the machines catches fire?' — you are doing system design."}},
        {"type": "callout", "id": "definition", "payload": {"title": "Working definition", "body": "System design is the process of choosing **what components** your system has, **how they communicate**, and **what trade-offs you accept** — so the system meets its requirements for scale, reliability, latency, cost, and maintainability.", "kind": "note"}},
        {"type": "diagram", "id": "diagram-layers", "payload": {"ascii": "  ┌─────────────────────────────────────────┐\n  │            Users (clients)              │\n  └──────────────────┬────────────────────┘\n                     │\n  ┌──────────────────▼────────────────────┐\n  │      CDN  +  Load Balancer             │  ← traffic enters here\n  └──────────────────┬────────────────────┘\n                     │\n  ┌──────────────────▼────────────────────┐\n  │         Application Layer             │  ← stateless services\n  │     (service A, service B, ...)       │\n  └────┬──────────┬──────────┬──────────┘\n       │          │          │\n  ┌────▼───┐ ┌────▼───┐ ┌────▼────┐\n  │ Cache  │ │  DB    │ │ Queue   │  ← state lives here\n  └────────┘ └────────┘ └─────────┘", "caption": "A typical web system: clients → edge → app → stateful stores. Every box is a design decision.", "voice_alt_text": "A typical web system architecture diagram. Users connect through a CDN and load balancer to a layer of stateless application services. The services read from and write to a cache, a database, and a message queue. Every box represents a design decision with trade-offs."}},
        {"type": "prose", "id": "what-you-design", "payload": {"text": "When you design a system, you are making decisions in five areas:\n\n1. **Components** — what services, databases, caches, queues, and storage systems exist.\n2. **Communication** — how they talk: synchronous (HTTP, gRPC), asynchronous (queues, pub/sub), or streaming.\n3. **Data** — where state lives, how it's stored, replicated, and partitioned.\n4. **Failure** — what happens when each component breaks, and how the system degrades gracefully.\n5. **Scale** — how the system behaves at 10 users, 10,000 users, and 10,000,000 users.\n\nEvery design decision is a trade-off. There are no free lunches."}},
        {"type": "callout", "id": "no-free-lunch", "payload": {"title": "The core truth", "body": "You cannot have maximum consistency, maximum availability, and maximum performance simultaneously. You cannot have a system that is infinitely scalable, perfectly reliable, and trivially simple. System design is the art of choosing **which trade-offs are acceptable for your specific problem**.", "kind": "note"}},
        {"type": "prose", "id": "interview-context", "payload": {"text": "In a system-design interview, the interviewer is not looking for a 'correct' answer — there usually isn't one. They are looking for:\n\n- **Clarification**: do you ask good questions before designing?\n- **Structure**: do you break the problem into requirements, capacity, API, data model, high-level design, deep dive, bottlenecks?\n- **Trade-off awareness**: do you name what you're giving up when you choose a technology?\n- **Communication**: can you explain your reasoning out loud?\n\nThis is why system design is a skill, not memorization. You practice it by designing systems and explaining your choices."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Which statement best captures what system design is?", "shape": "mcq", "options": ["Choosing the right framework and language for your app.", "Defining components, communication, data, failure, and scale trade-offs for a software system.", "Writing code that passes all tests.", "Deploying code to cloud infrastructure."], "answer_index": 1, "rationale": "Frameworks, tests, and deployment are all implementation details. System design is the higher-level discipline of deciding what components exist, how they communicate, where data lives, how failures are handled, and how the system scales. It is about architecture and trade-offs, not specific tools.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "In a system design interview, what is the interviewer primarily evaluating?", "shape": "mcq", "options": ["Whether you can recite the CAP theorem from memory.", "Whether you have built the exact system before.", "Your ability to clarify requirements, structure the problem, and reason about trade-offs.", "How fast you can draw boxes on a whiteboard."], "answer_index": 2, "rationale": "Interviewers evaluate structured thinking and trade-off reasoning, not memorization. They want to see you clarify ambiguous requirements, break the problem into manageable pieces, and explain why you chose each technology and what you gave up. A candidate who designs a simple, well-reasoned system beats one who draws a complex diagram without explaining trade-offs.", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Forces explicit reasoning about scale, reliability, and cost.", "Catches problems before they become production incidents.", "Creates a shared language for engineering teams."], "cons": ["No single 'correct' answer — judgement-based and subjective.", "Time-consuming; easy to over-engineer or under-engineer.", "Requires broad knowledge of many technologies and patterns."]},
    "failure_modes": ["Over-engineering: adding queues, caches, and microservices before the system needs them.", "Under-engineering: assuming a single server and single database will scale forever.", "Cargo-culting: copying a big-company architecture (e.g., Netflix) without understanding why they made those choices.", "Ignoring failure modes: designing only for the happy path."],
    "common_mistakes": ["Jumping into a solution before clarifying requirements and constraints.", "Memorizing architectures instead of understanding trade-offs.", "Treating 'scalability' as a single axis — it has throughput, latency, and data-volume dimensions.", "Forgetting that the simplest design that meets requirements is usually the best design."],
    "where_you_see_it": ["Every production software system ever built.", "Every system-design interview at every tech company.", "Every architecture review and incident postmortem."],
    "interview_prompts": ["What is system design, and why does it matter?", "Walk me through how you would approach designing a system you've never seen before.", "What's the difference between system design and software architecture?"],
    "real_system_mappings": [{"system": "Netflix", "how": "Microservices architecture with hundreds of services, each designed for a specific scale and failure profile. Documented openly in their tech blog."}, {"system": "Uber", "how": "Domain-oriented microservices with explicit dispatch, geospatial, and pricing subsystems. Evolved from a monolith to a distributed system over years."}],
    "status": "published",
})

write_concept('how-to-approach-system-design', {
    "slug": "how-to-approach-system-design",
    "version": 2,
    "title": "How to Approach System Design",
    "phase": "foundations",
    "area": "Foundations",
    "estimated_minutes": 10,
    "difficulty": "core",
    "summary": "A structured approach to system design: clarify requirements → estimate capacity → define APIs → model data → design high-level architecture → deep-dive components → identify bottlenecks → discuss trade-offs. Following this skeleton prevents you from jumping straight into a solution and missing critical constraints.",
    "why_it_matters": "Most system design interview failures and most production incidents come from skipping requirements clarification. People jump into 'use Kafka and Cassandra' before they know the read/write ratio, the latency target, or the failure requirements. A structured approach prevents this.",
    "prerequisites": ["what-is-system-design"],
    "related": ["performance-vs-scalability", "latency-vs-throughput", "capacity-estimation"],
    "used_in": ["Every system-design interview.", "Every real architecture review."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "System design problems are open-ended by design. 'Design Twitter' could mean anything — a toy project for 100 users or a global platform for 300 million. The first job is to **narrow the problem**. The second is to **structure your thinking** so you don't miss critical constraints.\n\nThe 8-step skeleton below works for interviews and real architecture reviews alike. Use it as a checklist, not a rigid script."}},
        {"type": "diagram", "id": "approach-flow", "payload": {"ascii": "  1. Clarify requirements\n      │  (functional + non-functional)\n      ▼\n  2. Capacity estimation\n      │  (QPS, storage, bandwidth)\n      ▼\n  3. APIs / interfaces\n      │  (what does the system DO?)\n      ▼\n  4. Data model\n      │  (what entities, what store?)\n      ▼\n  5. High-level design\n      │  (boxes and arrows)\n      ▼\n  6. Deep dive\n      │  (the hard components)\n      ▼\n  7. Bottlenecks & failures\n      │  (what breaks first?)\n      ▼\n  8. Trade-offs & alternatives", "caption": "The 8-step system design skeleton. Each step constrains the next.", "voice_alt_text": "A vertical flowchart showing the 8-step system design approach: clarify requirements, estimate capacity, define APIs, model data, high-level design, deep dive, bottlenecks and failures, and trade-offs. Each step flows into the next, and each constrains the decisions you make later."}},
        {"type": "prose", "id": "step1", "payload": {"text": "**Step 1: Clarify requirements.** Before designing anything, ask:\n\n- What are the **functional requirements**? (What does the system do? e.g., 'users can post tweets, follow others, see a feed.')\n- What are the **non-functional requirements**? (How well must it do it? e.g., '99.9% availability, 200ms p99 latency for reads, 10M DAU.')\n- What is **out of scope**? (e.g., 'no recommendation algorithm in v1.')\n\nThis step takes 2-3 minutes in an interview and prevents 30 minutes of wasted design work."}},
        {"type": "callout", "id": "clarify-example", "payload": {"title": "Example: 'Design Twitter'", "body": "Before drawing anything, ask: 'Do we need to support real-time feed updates, or is eventual consistency acceptable? What's the expected DAU? Is the feed personalized (algorithmic) or just chronological? Do we need search? What about media (images, video)?' The answers completely change the architecture.", "kind": "note"}},
        {"type": "prose", "id": "step2", "payload": {"text": "**Step 2: Capacity estimation.** Translate requirements into numbers:\n\n- **QPS** (queries per second): 10M DAU × ~20 requests/day / 86400s ≈ 2,300 QPS average. Peak = 5-10x average.\n- **Storage**: 10M users × 10 tweets/day × 200 bytes = 20GB/day = 7.3TB/year. Add 3x for media.\n- **Bandwidth**: 2,300 QPS × 50KB per response = 115 MB/s = ~1 Gbps.\n- **Cache**: if 80% of traffic hits 20% of content, cache ~20% of active data.\n\nThese numbers don't need to be exact — they need to be **order-of-magnitude correct** so you can choose the right technology."}},
        {"type": "prose", "id": "step3-4", "payload": {"text": "**Step 3: APIs.** Define the contract. For Twitter: `POST /tweets`, `GET /feed`, `POST /follow`. This forces you to think about what the system actually does, not just what it stores.\n\n**Step 4: Data model.** What entities exist? (User, Tweet, Follow.) What store? (SQL for transactions, NoSQL for scale, object storage for media.) How are they related? This is where you decide between PostgreSQL, Cassandra, DynamoDB, etc."}},
        {"type": "prose", "id": "step5-6", "payload": {"text": "**Step 5: High-level design.** Draw the boxes: clients → CDN → load balancer → app services → cache/database/queue. Keep it simple. This is the 30,000-foot view.\n\n**Step 6: Deep dive.** Pick the 1-2 hardest components and design them in detail. For Twitter, that's the **feed generation** (fan-out on write vs fan-out on read) and the **timeline cache**. Don't deep-dive every component — pick the ones that are genuinely hard."}},
        {"type": "prose", "id": "step7-8", "payload": {"text": "**Step 7: Bottlenecks and failures.** Walk through what breaks:\n- What if the primary database dies?\n- What if a cache cluster dies?\n- What if traffic spikes 10x?\n- What if a single user goes viral?\n\n**Step 8: Trade-offs and alternatives.** Explicitly name what you gave up. 'I chose fan-out on write for low read latency, but it costs write amplification and makes deletion hard.' This is the step that separates senior from junior — the ability to articulate trade-offs."}},
        {"type": "callout", "id": "anti-pattern", "payload": {"title": "Anti-pattern: jumping to technology", "body": "The most common mistake is hearing 'design Twitter' and immediately saying 'use Kafka, Cassandra, and Redis'. Technology choices come AFTER you understand requirements, capacity, and data model. Naming technologies too early signals you're memorizing rather than reasoning.", "kind": "warning"}},
        {"type": "quiz", "id": "q1", "payload": {"question": "You're asked to 'Design a URL shortener like bit.ly'. What should you do FIRST?", "shape": "mcq", "options": ["Choose between PostgreSQL and Cassandra.", "Draw the high-level architecture with a load balancer and app server.", "Clarify requirements: how many URLs per day? What's the read/write ratio? Custom aliases?", "Estimate the storage needed for 5 years of URLs."], "answer_index": 2, "rationale": "Always clarify requirements before estimating capacity or choosing technology. Without knowing the read/write ratio (shorteners are typically 100:1 read-heavy) and the scale (1M URLs/day vs 100M), you cannot choose the right database, cache strategy, or hashing approach. Capacity estimation (step 2) comes after clarification (step 1).", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "During a system design interview, you've drawn the high-level architecture. What should you do next?", "shape": "mcq", "options": ["Start over if the interviewer didn't seem impressed.", "Pick the 1-2 hardest components and deep-dive them, then identify bottlenecks and trade-offs.", "List every technology you'd use and why.", "Ask the interviewer if you're done."], "answer_index": 1, "rationale": "After high-level design (step 5), you should deep-dive the hardest components (step 6) — the ones where the design is non-obvious and where trade-offs matter most. Then identify bottlenecks and failures (step 7) and articulate trade-offs (step 8). This shows structured thinking and depth, not breadth.", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Prevents premature commitment to a technology.", "Surfaces constraints before they become incidents.", "Creates a shared structure that teams and interviewers can follow."], "cons": ["Can feel rigid — real systems sometimes need creative leaps.", "Takes 30-45 minutes; not every problem deserves full treatment.", "Can produce over-engineered designs if you follow every step dogmatically."]},
    "failure_modes": ["Skipping requirements clarification → designing the wrong system.", "Jumping to technology before understanding data and scale.", "Deep-diving every component instead of the 1-2 hard ones.", "Not articulating trade-offs — making the design feel arbitrary."],
    "common_mistakes": ["Treating the 8 steps as a script instead of a checklist.", "Estimating capacity with made-up numbers instead of deriving them from requirements.", "Forgetting to discuss failure modes — interviewers always ask 'what breaks?'", "Choosing 'cool' technologies (Kafka, Cassandra) when simpler ones (PostgreSQL, Redis) would work."],
    "where_you_see_it": ["Every system-design interview at every tech company.", "Every real architecture review.", "Every good engineering design document."],
    "interview_prompts": ["Walk me through how you would approach designing a system you've never seen before.", "What questions do you ask before starting a system design?", "Why is capacity estimation important before choosing a database?"],
    "real_system_mappings": [{"system": "Google design docs", "how": "Google's engineering culture requires design docs that follow this structure: requirements, alternatives, proposed design, trade-offs. Documented in their engineering practices guide."}, {"system": "AWS architecture whitepapers", "how": "AWS Well-Architected Framework follows the same skeleton: requirements, capacity, design, bottlenecks, trade-offs."}],
    "status": "published",
})

write_concept('performance-vs-scalability', {
    "slug": "performance-vs-scalability",
    "version": 2,
    "title": "Performance vs Scalability",
    "phase": "foundations",
    "area": "Foundations",
    "estimated_minutes": 8,
    "difficulty": "core",
    "summary": "Performance is how fast a system handles a single request. Scalability is how well it handles more requests. They are related but distinct: a system can be fast and unscalable, or slow and scalable. Confusing them leads to bad architecture decisions.",
    "why_it_matters": "If you don't know whether your problem is a performance problem or a scalability problem, you'll apply the wrong solution. Adding more servers (scaling out) doesn't fix slow code. Optimizing an algorithm doesn't help if your single database is the bottleneck. Naming the problem correctly is half the solution.",
    "prerequisites": ["what-is-system-design"],
    "related": ["latency-vs-throughput", "horizontal-scaling"],
    "used_in": ["Every system that needs to handle growth."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "**Performance** measures how fast your system does one thing. **Scalability** measures how well it does many things. These sound similar, but they fail in different ways and need different fixes.\n\nA Formula 1 car has high performance (fast lap time) but poor scalability (only seats one). A city bus has lower performance (slower) but better scalability (seats 50). Neither is 'better' — they solve different problems."}},
        {"type": "callout", "id": "definition", "payload": {"title": "Definitions", "body": "**Performance**: how quickly a system responds to a given load. Measured in latency, throughput, resource utilization.\n\n**Scalability**: how well a system maintains performance as load increases. Measured in how throughput changes when you add resources.\n\nA system that handles 100 RPS at 50ms latency and 1000 RPS at 50ms latency is **scalable**. A system that handles 100 RPS at 50ms and 1000 RPS at 500ms is **fast but not scalable**.", "kind": "note"}},
        {"type": "diagram", "id": "perf-vs-scale", "payload": {"ascii": "  PERFORMANCE (single request)\n  ─────────────────────────────\n  Request → [Server] → Response\n             50ms\n\n  Question: how fast is one request?\n  Fix: optimize code, faster CPU, better algorithm\n\n\n  SCALABILITY (many requests)\n  ────────────────────────────\n  Request ─┐\n  Request ─┼─→ [Load Balancer] → [S1] [S2] [S3] [S4]\n  Request ─┘\n  10,000 RPS\n\n  Question: does latency stay flat as load grows?\n  Fix: add servers, partition data, cache", "caption": "Performance is about one request. Scalability is about the curve as load grows.", "voice_alt_text": "Two diagrams. The first shows performance: a single request hits one server and returns in 50 milliseconds. The question is how fast one request is. The fix is to optimize code or use a faster CPU. The second shows scalability: thousands of requests hit a load balancer that distributes them across four servers. The question is whether latency stays flat as load grows. The fix is to add servers, partition data, or cache."}},
        {"type": "prose", "id": "relationship", "payload": {"text": "Performance and scalability interact, but improving one doesn't always improve the other:\n\n- **Fast but not scalable**: A single PostgreSQL instance with a well-tuned query. Handles 100 RPS at 5ms. But at 10,000 RPS it falls over because one machine can't handle the connections.\n- **Scalable but not fast**: A distributed system across 100 nodes. Each request takes 200ms (slow) because of network hops, but the system handles 1M RPS without latency increasing.\n- **Both**: A system with a fast single-request path AND horizontal scalability. This is the goal — and it's hard."}},
        {"type": "callout", "id": "diagnose", "payload": {"title": "How to diagnose", "body": "If latency is high at low load → **performance problem**. Fix the code, the algorithm, or the hardware.\n\nIf latency is low at low load but increases as load grows → **scalability problem**. Add capacity (scale out), partition data (shard), or introduce caching.\n\nIf latency is high at all loads → you have both problems. Start with the performance problem; it's usually cheaper to fix.", "kind": "success"}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your API responds in 50ms when 100 users hit it, but takes 500ms when 1000 users hit it. Is this a performance problem or a scalability problem?", "shape": "mcq", "options": ["Performance — the code is too slow.", "Scalability — the system doesn't maintain performance as load grows.", "Both — you need to rewrite everything.", "Neither — 500ms is acceptable."], "answer_index": 1, "rationale": "The system is fast at low load (50ms) but degrades as load grows (500ms at 1000 users). This is a scalability problem — the system cannot maintain performance as load increases. The fix is to add capacity (scale out), introduce caching, or partition data — not to optimize the single-request code path.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "Which change is a performance optimization (not a scalability optimization)?", "shape": "mcq", "options": ["Adding a load balancer and 3 more app servers.", "Replacing a O(n²) sort with a O(n log n) sort.", "Sharding the database across 4 nodes.", "Adding a Redis cache in front of the database."], "answer_index": 1, "rationale": "Replacing a slow algorithm with a faster one improves single-request performance — the response time for one request drops. Adding load balancers, sharding, and caching are all scalability optimizations: they help the system handle more requests, but don't necessarily make any single request faster (and can even add latency through network hops).", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Naming the problem correctly points to the right fix.", "Performance optimizations are often cheap (code changes).", "Scalability optimizations are often additive (add more nodes)."], "cons": ["Performance and scalability can conflict: adding network hops for scalability can hurt single-request performance.", "Scalability fixes cost money (more servers).", "Performance fixes can introduce complexity (caching, async)."]},
    "failure_modes": ["Adding more servers when the code is slow (doesn't fix the problem).", "Optimizing algorithms when the database is the bottleneck.", "Caching everything when the real issue is connection pool exhaustion."],
    "common_mistakes": ["Confusing 'fast' with 'scalable'.", "Treating scalability as a single axis — it has throughput, latency, and data-volume dimensions.", "Forgetting that scalability has a cost (more servers = more money + more complexity)."],
    "where_you_see_it": ["Every system that needs to handle growth.", "Every performance review and capacity planning meeting.", "Every 'why is the app slow?' investigation."],
    "interview_prompts": ["What's the difference between performance and scalability? Give an example of each.", "If your system is slow, how do you decide whether to optimize code or add servers?", "Can a system be both high-performance and highly scalable? What's the tension?"],
    "real_system_mappings": [{"system": "Redis", "how": "Single-threaded, extremely fast per-request (performance). Scales by sharding across multiple Redis instances (scalability). The designers explicitly separated the two concerns."}, {"system": "Cassandra", "how": "Lower single-request performance than Redis (network hops, consensus), but linear horizontal scalability. Designed for scalability first."}],
    "status": "published",
})

write_concept('latency-vs-throughput', {
    "slug": "latency-vs-throughput",
    "version": 2,
    "title": "Latency vs Throughput",
    "phase": "foundations",
    "area": "Foundations",
    "estimated_minutes": 9,
    "difficulty": "core",
    "summary": "Latency is how long one operation takes. Throughput is how many operations happen per unit time. They are related but distinct: you can have high throughput with high latency (batch processing) or low latency with low throughput (single-user app). Knowing which one to optimize is a core system design skill.",
    "why_it_matters": "If you optimize throughput when your users care about latency, you'll build a system that handles lots of requests but feels slow. If you optimize latency when throughput matters, you'll build a system that feels fast but falls over under load. Most production systems need both — but they optimize them differently.",
    "prerequisites": ["performance-vs-scalability"],
    "related": ["availability-vs-consistency", "back-pressure"],
    "used_in": ["Every system that serves users or processes data."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "**Latency** is the time from 'I asked for something' to 'I got it.' Measured in milliseconds (or microseconds, or seconds). It's a per-operation metric.\n\n**Throughput** is how many operations complete per unit time. Measured in requests per second (RPS), messages per second, or transactions per second. It's an aggregate metric.\n\nA system can have low throughput and low latency (a personal blog), high throughput and high latency (batch ETL), or — the holy grail — high throughput and low latency (a well-designed API)."}},
        {"type": "diagram", "id": "latency-vs-throughput", "payload": {"ascii": "  LATENCY (per request)\n  ──────────────────────\n  Client sends request at t=0\n  Server responds at t=50ms\n  Latency = 50ms\n\n  THROUGHPUT (aggregate)\n  ──────────────────────\n  Server handles 10,000 requests\n  in 1 second\n  Throughput = 10,000 RPS\n\n  RELATIONSHIP:\n  Throughput ≈ concurrency / latency\n  (Little's Law)\n\n  To increase throughput:\n  • reduce latency (faster per request)\n  • increase concurrency (more parallel requests)\n  • or both", "caption": "Latency is per-request; throughput is aggregate. Little's Law connects them.", "voice_alt_text": "A diagram explaining latency versus throughput. Latency is the time from when a client sends a request to when the server responds — say, 50 milliseconds. Throughput is how many requests complete per second — say, 10,000 requests per second. They are related by Little's Law: throughput equals concurrency divided by latency. To increase throughput, you can reduce latency, increase concurrency, or both."}},
        {"type": "prose", "id": "little-law", "payload": {"text": "**Little's Law** connects them: `Throughput ≈ Concurrency / Latency`. If your system handles 100 concurrent requests at 50ms latency each, throughput ≈ 100 / 0.05 = 2,000 RPS. To increase throughput you can:\n- **Reduce latency** (faster per request) — optimize code, cache, index.\n- **Increase concurrency** (more parallel requests) — add servers, increase thread pool, use async I/O.\n- **Both** — the best systems do both."}},
        {"type": "callout", "id": "p99", "payload": {"title": "Always measure percentiles, not averages", "body": "Average latency hides tail latency. If 99 requests take 10ms and 1 takes 1000ms, the average is ~20ms — looks fine. But 1% of your users see a 1-second delay. Always report p50 (median), p95, and p99. SLOs are usually written against p99: '99% of requests complete in under 200ms.'", "kind": "warning"}},
        {"type": "prose", "id": "tradeoff", "payload": {"text": "Latency and throughput can conflict:\n- **Batching** increases throughput but adds latency (you wait for the batch to fill).\n- **Caching** reduces latency and increases throughput (fewer DB hits).\n- **Replication** can reduce read latency but add write latency (sync to replicas).\n- **Sharding** increases throughput but can add latency (cross-shard queries).\n\nThe right choice depends on what your users care about. A real-time game cares about latency. A data pipeline cares about throughput. A web API cares about both — but usually optimizes for p99 latency first, because a slow request feels worse than a rejected one."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your API averages 50ms latency. But users complain it 'feels slow'. What should you check?", "shape": "mcq", "options": ["The average is fine — users are wrong.", "The p99 latency — there may be a long tail of slow requests hidden by the average.", "The throughput — you need more servers.", "The database size."], "answer_index": 1, "rationale": "Averages hide tail latency. If 99% of requests take 10ms and 1% take 1000ms, the average is ~20ms — but 1 in 100 users experiences a 1-second delay, which feels very slow. Always measure p50, p95, and p99 percentiles. The complaint 'feels slow' almost always points to p99 or p99.9 latency, not the average.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "You're building a batch ETL pipeline that processes 10TB of data nightly. What should you optimize for?", "shape": "mcq", "options": ["Latency — each record should be processed as fast as possible.", "Throughput — maximize records processed per second, even if individual records are slow.", "Both equally.", "Neither — just make it work."], "answer_index": 1, "rationale": "Batch ETL is throughput-bound. No user is waiting for an individual record — the job just needs to finish before the next day. Batching, parallelism, and pipeline depth all increase throughput at the cost of per-record latency, which is the right trade-off for batch. (Latency matters only in the sense of total job completion time.)", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Latency optimizations (caching, indexing) often improve user experience directly.", "Throughput optimizations (batching, sharding) often reduce cost per operation.", "Little's Law gives a clear mental model for reasoning about both."], "cons": ["Latency and throughput can conflict (batching, replication, sharding add latency for throughput).", "Optimizing one without the other can create bottlenecks (fast code + single DB = not scalable).", "Percentile measurement is harder than average — requires real monitoring."]},
    "failure_modes": ["Optimizing average latency when p99 is the problem.", "Adding throughput (more servers) when latency is the bottleneck (slow code).", "Batching for throughput in a latency-sensitive system (makes it feel slower)."],
    "common_mistakes": ["Reporting average latency instead of p99.", "Treating 'fast' and 'scalable' as the same thing.", "Forgetting that throughput without latency targets is meaningless — 1M RPS at 30s latency is useless for most apps."],
    "where_you_see_it": ["Every API with SLOs (usually p99 latency + throughput targets).", "Every batch pipeline (throughput-bound).", "Every real-time system (latency-bound)."],
    "interview_prompts": ["What's the difference between latency and throughput? When do they conflict?", "What is Little's Law and how is it useful?", "Why do we measure p99 instead of average latency?", "Your system has high throughput but users say it feels slow. What do you investigate?"],
    "real_system_mappings": [{"system": "CDNs (Cloudflare, Fastly)", "how": "Optimize for latency — cache at the edge so users get content in <50ms globally. Throughput is achieved by massive parallelism across edge locations."}, {"system": "Kafka", "how": "Optimizes for throughput — batches messages, appends to logs sequentially. Per-message latency is higher than a synchronous queue, but throughput is dramatically higher."}],
    "status": "published",
})

write_concept('availability-vs-consistency', {
    "slug": "availability-vs-consistency",
    "version": 2,
    "title": "Availability vs Consistency",
    "phase": "foundations",
    "area": "Foundations",
    "estimated_minutes": 10,
    "difficulty": "core",
    "summary": "Availability means every request gets a response. Consistency means every read sees the latest write. In distributed systems, you often have to choose between them — especially during network partitions. This trade-off is the heart of CAP theorem.",
    "why_it_matters": "Every distributed system makes this trade-off, whether explicitly or implicitly. A bank ledger prioritizes consistency (never show a wrong balance). A social feed prioritizes availability (show something, even if slightly stale). Choosing wrong means either lost money or angry users.",
    "prerequisites": ["latency-vs-throughput"],
    "related": ["cap-theorem", "consistency-patterns", "availability-patterns"],
    "used_in": ["Every distributed database and every multi-node service."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "**Availability** means every non-failed node returns a response (not an error or timeout) for every request. The response might be stale, but it's not an error.\n\n**Consistency** (in the CAP sense, i.e., linearizability) means every read sees the most recent write, as if there were a single copy of the data.\n\nIn a single-machine system, you get both for free — there's only one copy. In a distributed system, when the network between nodes fails (a partition), you must choose: refuse to respond (lose availability) or respond with possibly-stale data (lose consistency)."}},
        {"type": "diagram", "id": "av-vs-cons", "payload": {"ascii": "  CONSISTENCY (linearizable)\n  ──────────────────────────\n  Write to Node A\n      │\n      ▼\n  Node A syncs to Node B ──→ Node B\n      │\n      ▼\n  Read from Node B → sees the write\n\n  Guarantee: every read sees the latest write.\n  Cost: if Node B can't reach Node A, reads fail.\n\n\n  AVAILABILITY (eventually consistent)\n  ────────────────────────────────────\n  Write to Node A ──→ Node A responds OK\n  Read from Node B  ──→ Node B responds (maybe stale)\n\n  Guarantee: every request gets a response.\n  Cost: reads might see old data until replication catches up.", "caption": "Consistency requires coordination (and refuses during partition). Availability responds always (but may be stale).", "voice_alt_text": "Two diagrams comparing consistency and availability. In the consistency model: a write goes to Node A, which synchronizes to Node B before acknowledging. A subsequent read from Node B sees the latest write. The guarantee is that every read sees the latest write, but the cost is that if Node B can't reach Node A, reads fail. In the availability model: a write goes to Node A and gets an immediate OK. A read from Node B gets an immediate response, but it might be stale. The guarantee is that every request gets a response, but the cost is that reads might see old data until replication catches up."}},
        {"type": "prose", "id": "examples", "payload": {"text": "Real-world examples make this concrete:\n\n- **Bank balance**: must be consistent. If you transfer $100, a subsequent read MUST reflect it. If the system is partitioned, the bank refuses the read (unavailable) rather than showing a wrong balance.\n- **Social media feed**: can be eventually consistent. If you post a tweet and a follower's feed updates 5 seconds later, that's fine. The system stays available during partitions.\n- **Shopping cart**: must be consistent. You can't show a wrong item count — users would lose trust.\n- **Like counter**: can be eventually consistent. '1,234 likes' vs '1,235 likes' doesn't matter for a few seconds."}},
        {"type": "callout", "id": "choose", "payload": {"title": "How to choose", "body": "Ask: 'What happens if the user sees stale data?'\n\n- If it causes **financial loss, data corruption, or safety issues** → choose consistency.\n- If it causes **minor inconvenience or temporary confusion** → choose availability.\n- Most systems have **mixed requirements**: consistent for writes (payments), eventually consistent for reads (feeds). This is the common pattern.", "kind": "success"}},
        {"type": "prose", "id": "beyond-cap", "payload": {"text": "CAP theorem (next lesson) formalizes this trade-off during partitions. But even without partitions, there's a latency-vs-consistency trade-off: stronger consistency requires more coordination (quorum reads/writes, consensus rounds), which adds latency. This is captured by **PACELC**: during a Partition, choose A or C; Else (normal operation), choose L (latency) or C."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "You're designing a ride-sharing app's driver location tracker. Drivers broadcast their location every 4 seconds. Should the tracker prioritize consistency or availability?", "shape": "mcq", "options": ["Consistency — every rider must see the exact current driver location.", "Availability — riders should always see a driver location, even if it's a few seconds stale.", "Both — no trade-off needed.", "Neither — location tracking is always exact."], "answer_index": 1, "rationale": "Driver locations update every 4 seconds anyway, so a few seconds of staleness is inherent in the system. Refusing to show a driver's location during a network partition (consistency) would make the app feel broken and prevent ride matching. Availability is the right choice — show the last known location, which is at most 4 seconds old. This is why Uber uses eventually consistent systems for location tracking.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "Your payment system processes credit card charges. During a network partition between your primary DB and the replica, a user checks their balance. What should happen?", "shape": "mcq", "options": ["Show the balance from the replica — it's probably close enough.", "Refuse the read and return an error — the balance might be wrong.", "Always show $0 to be safe.", "Crash the app."], "answer_index": 1, "rationale": "For payments, consistency is critical. If the replica hasn't received the latest transaction, the user might see a higher balance than they actually have, leading to overdrafts and disputes. Refusing the read (returning an error or 'try again later') is the correct behavior — it's better to be temporarily unavailable than to show wrong financial data. This is why banks prioritize consistency over availability.", "difficulty": "interview"}}
    ],
    "trade_offs": {"pros": ["Consistency prevents bugs where users see wrong data (critical for finance, inventory, safety).", "Availability keeps the system usable during partitions (critical for social, content, real-time).", "Naming the trade-off explicitly prevents 'why is this slow/stale?' confusion later."], "cons": ["Strong consistency requires coordination (quorum, consensus) — adds latency and reduces availability during partitions.", "Eventual consistency requires handling stale reads in application code (conflict resolution, idempotency).", "Mixed systems (consistent writes, eventually consistent reads) add complexity."]},
    "failure_modes": ["Choosing availability for financial data — leads to lost money and disputes.", "Choosing consistency for social feeds — makes the system feel slow and unavailable.", "Forgetting that 'eventual consistency' means 'eventually converged', not 'eventually correct' — conflicts can still occur."],
    "common_mistakes": ["Treating 'consistency' as binary — it's a spectrum (linearizable, sequential, causal, eventual).", "Assuming 'eventually consistent' means 'always eventually correct' — it means eventually converged, which can still be wrong.", "Forgetting that strong consistency has a latency cost, not just an availability cost."],
    "where_you_see_it": ["Every distributed database (Cassandra = AP, Spanner = CP).", "Every multi-region service (must choose per-operation).", "Every payment system (must be consistent for writes)."],
    "interview_prompts": ["What's the difference between availability and consistency? When would you choose each?", "Give an example of a system that should prioritize consistency, and one that should prioritize availability.", "Can you have both? What's the cost?"],
    "real_system_mappings": [{"system": "DynamoDB", "how": "Configurable consistency: eventually consistent reads (default) for availability, or strongly consistent reads (optional) for correctness. The user chooses per request."}, {"system": "Google Spanner", "how": "Strongly consistent (CP) using Paxos consensus across regions. Trades higher latency for consistency — used for financial systems like AdWords billing."}],
    "status": "published",
})

print("\n✅ Foundations concepts written")
