#!/usr/bin/env python3
"""Generate deep content for Networking priority concepts."""
import json, os
CONCEPTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'content', 'concepts')

def write_concept(slug, data):
    fpath = os.path.join(CONCEPTS_DIR, f'{slug}.json')
    with open(fpath, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write('\n')
    print(f'  Wrote {slug} ({len(data.get("blocks",[]))} blocks)')

write_concept('http', {
    "slug": "http",
    "version": 2,
    "title": "HTTP — HyperText Transfer Protocol",
    "phase": "networking-communication",
    "area": "Networking & Communication",
    "estimated_minutes": 11,
    "difficulty": "core",
    "summary": "HTTP is the application-layer protocol that powers the web. It is request-response, stateless, and text-based. Understanding HTTP methods, status codes, headers, and the evolution from HTTP/1.1 to HTTP/2 to HTTP/3 is fundamental to every web system design.",
    "why_it_matters": "Every web API, every browser request, every microservice communication (over REST) uses HTTP. Knowing its semantics — what methods are safe vs idempotent, what status codes mean, how headers affect caching — is non-negotiable for system design.",
    "prerequisites": ["how-the-internet-works"],
    "related": ["tcp", "rest", "tls"],
    "used_in": ["Every web request.", "Every REST API.", "Most microservice communication."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "HTTP is a **request-response** protocol: a client sends a request, the server sends a response. It is **stateless** — each request is independent, and the server doesn't remember previous requests (unless you add cookies or sessions).\n\nThis statelessness is both a strength and a weakness: it makes HTTP easy to scale (any server can handle any request) but means the application must manage state through other means (cookies, tokens, server-side sessions)."}},
        {"type": "diagram", "id": "http-flow", "payload": {"ascii": "  Client (browser)                     Server\n  ─────────────────                    ─────\n\n  1. TCP connection ──────────────────→\n\n  2. Request:\n     GET /users/42 HTTP/1.1\n     Host: api.example.com\n     Accept: application/json\n                                        ────→\n\n  3. Response:\n                                        ←────\n     HTTP/1.1 200 OK\n     Content-Type: application/json\n     Content-Length: 47\n\n     {\"id\":42,\"name\":\"Ada\",\"role\":\"admin\"}\n\n  4. TCP connection closed (HTTP/1.1)\n     or reused (HTTP/2)", "caption": "A single HTTP request-response cycle over TCP.", "voice_alt_text": "A diagram of an HTTP request-response cycle. The client opens a TCP connection to the server, sends a request with a method, path, version, and headers, then receives a response with a status line, headers, and a body. In HTTP/1.1 the connection is then closed; in HTTP/2 it can be reused."}},
        {"type": "prose", "id": "methods", "payload": {"text": "HTTP methods have specific semantics:\n\n- **GET**: fetch a resource. **Safe** (no side effects) and **idempotent** (repeating it gives the same result).\n- **POST**: create a resource. Neither safe nor idempotent.\n- **PUT**: replace a resource. Not safe, but idempotent.\n- **DELETE**: remove a resource. Not safe, but idempotent.\n- **PATCH**: partially update a resource. Not necessarily idempotent.\n\n**Safe** methods can be cached and prefetched. **Idempotent** methods can be safely retried — this matters for unreliable networks."}},
        {"type": "callout", "id": "idempotency", "payload": {"title": "Why idempotency matters", "body": "If a network blip causes your payment request to time out, should you retry? If the method is idempotent (PUT, DELETE), yes — retrying is safe. If it's not (POST), retrying might charge the user twice. This is why payment APIs use idempotency keys: the client sends a unique ID with each request, and the server deduplicates.", "kind": "note"}},
        {"type": "prose", "id": "status-codes", "payload": {"text": "Status codes tell the client what happened:\n\n- **2xx Success**: 200 OK, 201 Created, 204 No Content\n- **3xx Redirect**: 301 Moved Permanently, 304 Not Modified (cache hit)\n- **4xx Client error**: 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 429 Too Many Requests\n- **5xx Server error**: 500 Internal Server Error, 502 Bad Gateway, 503 Service Unavailable\n\nIn system design, 429 (rate limited) and 503 (unavailable) are especially important — they signal the client to back off or retry."}},
        {"type": "prose", "id": "versions", "payload": {"text": "HTTP has evolved to address performance:\n\n- **HTTP/1.1** (1997): text-based, one request per TCP connection (later, pipelining). Head-of-line blocking.\n- **HTTP/2** (2015): binary framing, multiplexing (multiple requests over one connection), header compression (HPACK). Solves head-of-line blocking at the HTTP level.\n- **HTTP/3** (2022): runs over QUIC (UDP), eliminates TCP head-of-line blocking entirely, faster connection setup (0-RTT).\n\nMost modern APIs use HTTP/2. Browsers default to HTTP/3 where supported. The semantics (methods, status codes, headers) are the same — only the transport changes."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your payment API receives a POST /charges request, but the network times out before you get a response. The user might have been charged, or might not have. What should you do?", "shape": "mcq", "options": ["Retry the POST immediately — it's probably fine.", "Don't retry — POST is not idempotent, you might double-charge.", "Always retry with the same request body.", "Convert the POST to a PUT."], "answer_index": 1, "rationale": "POST is not idempotent — retrying could create a second charge. The correct pattern is to use an idempotency key: the client generates a unique ID for this logical operation and sends it with the request. The server stores the key and the result; if it sees the same key again, it returns the stored result instead of re-processing. Stripe's API uses this pattern. Without an idempotency key, the safe behavior is to NOT retry — instead, query the system to check whether the charge went through.", "difficulty": "interview"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "What is the main performance improvement of HTTP/2 over HTTP/1.1?", "shape": "mcq", "options": ["HTTP/2 uses UDP instead of TCP.", "HTTP/2 allows multiplexing multiple requests over a single TCP connection.", "HTTP/2 compresses the response body.", "HTTP/2 removes the need for TLS."], "answer_index": 1, "rationale": "HTTP/1.1 opens a separate TCP connection per request (or uses pipelining, which suffers from head-of-line blocking). HTTP/2 uses binary framing to multiplex multiple requests over a single TCP connection — so a slow request doesn't block faster ones. HTTP/3 goes further by using QUIC (UDP) to eliminate TCP-level head-of-line blocking too. HTTP/2 does not compress bodies or remove TLS — those are separate concerns.", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Stateless — easy to scale (any server handles any request).", "Text-based (HTTP/1.1) — easy to debug.", "Wide support — every language, every platform.", "Caching built into the protocol (Cache-Control, ETag)."], "cons": ["Request-response only — not suitable for server push (use WebSockets or SSE).", "Text-based HTTP/1.1 is inefficient (headers sent as text every time).", "Connection overhead — each TCP connection costs time (mitigated by HTTP/2 multiplexing)."]},
    "failure_modes": ["Head-of-line blocking in HTTP/1.1 (a slow request blocks others on the same connection).", "Excessive header size — cookies can bloat requests to several KB.", "Connection exhaustion — too many concurrent connections overwhelm the server."],
    "common_mistakes": ["Using GET for operations with side effects (violates HTTP semantics, breaks caching).", "Treating POST as idempotent (it's not — retries can duplicate).", "Returning 200 for errors — use proper 4xx/5xx codes so clients can handle them correctly."],
    "where_you_see_it": ["Every web request.", "Every REST API.", "Most microservice communication."],
    "interview_prompts": ["What's the difference between HTTP/1.1, HTTP/2, and HTTP/3?", "Which HTTP methods are idempotent, and why does it matter?", "How would you design an API to be safely retryable?"],
    "real_system_mappings": [{"system": "Stripe API", "how": "Uses idempotency keys for all POST requests so clients can safely retry payment operations without double-charging."}, {"system": "Cloudflare", "how": "Serves HTTP/3 to all clients by default, reducing connection latency globally."}],
    "status": "published",
})

write_concept('rest', {
    "slug": "rest",
    "version": 2,
    "title": "REST — Representational State Transfer",
    "phase": "networking-communication",
    "area": "Networking & Communication",
    "estimated_minutes": 12,
    "difficulty": "core",
    "summary": "REST is an architectural style for APIs that uses HTTP verbs on resources identified by URLs. It is stateless, cacheable, and uniform. Most public web APIs use REST (or something close to it) because it is simple, widely understood, and works over standard HTTP.",
    "why_it_matters": "REST is the default API style for most web systems. Knowing how to design good REST APIs — resource naming, status codes, pagination, versioning — is a core skill. Choosing REST vs gRPC vs GraphQL is a common system-design decision.",
    "prerequisites": ["http"],
    "related": ["graphql", "rpc", "grpc", "api-design"],
    "used_in": ["Almost every public web API.", "Most microservice communication."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "REST (Representational State Transfer) is not a protocol — it's an **architectural style** defined by Roy Fielding in 2000. It constrains how you design APIs over HTTP so they are scalable, simple, and cacheable.\n\nThe core idea: treat everything as a **resource** identified by a URL, and use HTTP verbs (GET, POST, PUT, DELETE) to act on those resources."}},
        {"type": "diagram", "id": "rest-mapping", "payload": {"ascii": "  RESOURCE: /users/42\n  ─────────────────────\n\n  GET    /users/42      → fetch user 42\n  POST   /users         → create a new user\n  PUT    /users/42      → replace user 42\n  PATCH  /users/42      → partially update user 42\n  DELETE /users/42      → delete user 42\n  GET    /users/42/posts → fetch posts by user 42\n\n  NESTED RESOURCES:\n  /users/42/posts/101/comments", "caption": "REST maps HTTP verbs to CRUD operations on resource URLs.", "voice_alt_text": "A diagram showing how REST maps HTTP verbs to operations on a resource URL. GET /users/42 fetches user 42. POST /users creates a new user. PUT /users/42 replaces user 42. PATCH partially updates. DELETE removes. Nested resources like /users/42/posts/101/comments express relationships."}},
        {"type": "prose", "id": "constraints", "payload": {"text": "REST has 6 constraints (Fielding's original definition):\n\n1. **Client-server**: separation of concerns. UI (client) and data (server) evolve independently.\n2. **Stateless**: each request contains all info needed. No server-side session. Enables scaling.\n3. **Cacheable**: responses declare if they're cacheable (Cache-Control, ETag). Improves performance.\n4. **Uniform interface**: resources identified by URLs, manipulated via representations (JSON/XML), self-descriptive messages, HATEOAS.\n5. **Layered**: client doesn't know if it's talking to the server directly or through a proxy/CDN.\n6. **Code-on-demand** (optional): server can send executable code (JavaScript) to the client.\n\nMost 'REST APIs' in practice only follow the first 3-4 constraints. True HATEOAS (Hypermedia As The Engine Of Application State) is rare."}},
        {"type": "callout", "id": "rest-vs-rpc", "payload": {"title": "REST vs RPC", "body": "REST thinks in terms of resources and verbs: `DELETE /users/42`. RPC thinks in terms of actions: `POST /deleteUser {id: 42}`. REST is more uniform and cacheable; RPC is more natural for complex operations. gRPC (later lesson) is a modern, high-performance RPC framework.", "kind": "note"}},
        {"type": "prose", "id": "best-practices", "payload": {"text": "Good REST API design:\n\n- **Plural nouns**: `/users` not `/user`. `/users/42/posts` not `/getUserPosts`.\n- **Versioning**: `/v1/users` or `Accept: application/vnd.api+json;version=1`. Never break existing clients.\n- **Pagination**: `GET /users?page=2&limit=20` or cursor-based `GET /users?after=abc123`.\n- **Status codes**: 200 OK, 201 Created, 204 No Content, 400 Bad Request, 404 Not Found, 429 Too Many Requests, 500 Internal Server Error.\n- **Filtering**: `GET /users?role=admin&active=true` — query params for filtering, not separate endpoints.\n- **Consistent error format**: `{\"error\": {\"code\": \"NOT_FOUND\", \"message\": \"User 42 not found\"}}`"}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Which URL design is most RESTful?", "shape": "mcq", "options": ["POST /createUser with body {name: 'Ada'}", "GET /getUserById?id=42", "POST /users with body {name: 'Ada'}", "GET /users/42/create"], "answer_index": 2, "rationale": "REST uses plural nouns for resources and HTTP verbs for actions. POST /users creates a new user resource — the verb (POST) implies creation, and /users is the collection. Options 1 and 2 embed the action in the URL (RPC style), which is not RESTful. Option 4 doesn't make sense semantically.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "Your REST API returns a list of 10,000 users. How should you handle this?", "shape": "mcq", "options": ["Return all 10,000 in one response — simpler for clients.", "Return a 413 Payload Too Large error.", "Paginate: return 20-50 per page with cursor or offset pagination.", "Return a 503 and ask the client to retry later."], "answer_index": 2, "rationale": "Returning 10,000 records in one response is slow, memory-intensive, and unusable for most clients. Pagination is the standard solution — return a page of 20-50 records with a cursor or offset to fetch the next page. Cursor-based pagination is preferred for large datasets (it's stable under inserts), but offset pagination is simpler. 413 and 503 don't solve the problem — they just refuse it.", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Simple and widely understood — every developer knows HTTP.", "Cacheable — HTTP caching (ETag, Cache-Control) works out of the box.", "Stateless — easy to scale (any server handles any request).", "Browser-friendly — works without special client libraries."], "cons": ["Over-fetching or under-fetching — the client gets the whole resource or must make multiple requests. (GraphQL solves this.)", "Text-based (JSON) — less efficient than binary protocols (gRPC/Protobufs).", "Request-response only — not suitable for streaming or server push (use WebSockets/SSE).", "Multiple round trips — fetching related resources requires multiple requests."]},
    "failure_modes": ["Returning 200 OK with an error body — breaks HTTP semantics and client error handling.", "Using GET for operations with side effects — breaks caching and violates HTTP.", "No pagination — large responses crash clients and servers.", "Breaking changes without versioning — existing clients stop working."],
    "common_mistakes": ["Embedding verbs in URLs (e.g., /getUser) — use HTTP verbs instead.", "Forgetting idempotency — POST is not idempotent, so retries can duplicate resources.", "Returning huge nested objects — use pagination and expansion (?expand=posts)."],
    "where_you_see_it": ["Almost every public web API (GitHub, Stripe, Twitter).", "Most microservice communication over HTTP.", "Mobile app backends."],
    "interview_prompts": ["What are the REST constraints? Which ones do most 'REST APIs' actually follow?", "REST vs GraphQL vs gRPC — when would you choose each?", "How do you version a REST API?"],
    "real_system_mappings": [{"system": "GitHub API", "how": "Textbook REST: plural nouns, HTTP verbs, pagination via Link headers, versioning via URL (/v3/), HATEOAS links in responses."}, {"system": "Stripe API", "how": "REST with idempotency keys and expandable resources (?expand[]=customer) to avoid over-fetching."}],
    "status": "published",
})

write_concept('horizontal-scaling', {
    "slug": "horizontal-scaling",
    "version": 2,
    "title": "Horizontal Scaling",
    "phase": "scaling-performance",
    "area": "Scaling & Performance",
    "estimated_minutes": 11,
    "difficulty": "core",
    "summary": "Horizontal scaling means adding more machines (nodes) to handle more load, rather than making one machine bigger. It is the primary way modern systems scale — but it requires statelessness, distributed data, and careful failure handling.",
    "why_it_matters": "Every large system scales horizontally. Vertical scaling (bigger machine) has a hard ceiling — the biggest server you can buy. Horizontal scaling has no theoretical ceiling — add another node. But it introduces distributed systems problems: state management, consistency, network failures.",
    "prerequisites": ["load-balancers"],
    "related": ["vertical-scaling", "replication", "sharding", "microservices"],
    "used_in": ["Every large-scale web system.", "Every cloud-native architecture."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "**Vertical scaling** (scale up) means making your single server bigger — more CPU, more RAM, a faster SSD. **Horizontal scaling** (scale out) means adding more servers and distributing load across them.\n\nVertical scaling is simpler — you don't have to deal with distributed systems. But it has a ceiling: the biggest server AWS offers is `u-6tb1.metal` (6TB RAM, ~$10k/month). If you need more, you must scale horizontally."}},
        {"type": "diagram", "id": "vertical-vs-horizontal", "payload": {"ascii": "  VERTICAL (scale up)\n  ───────────────────\n  [Server: 4 CPU, 16GB]\n       ↓ upgrade\n  [Server: 32 CPU, 128GB]\n       ↓ upgrade\n  [Server: 128 CPU, 2TB]  ← ceiling\n\n  Pros: simple, no code changes.\n  Cons: hard ceiling, downtime to upgrade,\n        single point of failure.\n\n\n  HORIZONTAL (scale out)\n  ─────────────────────\n  [Server A]  [Server B]\n       ↓ add more\n  [A] [B] [C] [D] [E] [F]  ← no ceiling\n\n  Pros: no ceiling, no downtime, fault-tolerant.\n  Cons: requires statelessness, distributed data,\n        load balancing, harder debugging.", "caption": "Vertical scaling has a ceiling. Horizontal scaling does not — but it requires distributed systems.", "voice_alt_text": "Two diagrams. Vertical scaling: one server is upgraded from 4 CPUs to 32 to 128 — but there's a hard ceiling, and upgrades require downtime. Horizontal scaling: multiple servers are added behind a load balancer — no ceiling, no downtime, but requires statelessness and distributed data."}},
        {"type": "prose", "id": "statelessness", "payload": {"text": "The single most important requirement for horizontal scaling is **statelessness**: each server must be able to handle any request without depending on local state (in-memory sessions, local file uploads, per-server caches).\n\nIf server A holds a user's session in memory, and the load balancer sends the next request to server B, the user is logged out. To scale horizontally, you must move all state to shared storage:\n\n- **Sessions** → Redis or a shared database.\n- **File uploads** → object storage (S3, R2).\n- **Cache** → distributed cache (Redis, Memcached).\n- **Database** → shared database (possibly sharded)."}},
        {"type": "callout", "id": "sticky-sessions", "payload": {"title": "Sticky sessions are a trap", "body": "Some load balancers support 'sticky sessions' — routing the same user to the same server so you can keep sessions in memory. This seems easy but defeats horizontal scaling's fault tolerance: if that server dies, all its users lose their sessions. Always move sessions to shared storage (Redis) instead.", "kind": "warning"}},
        {"type": "prose", "id": "data-scaling", "payload": {"text": "Once your app servers are stateless, the next bottleneck is the **database**. A single database can only handle so many connections and so much data. The scaling path:\n\n1. **Read replicas** — replicate writes to read-only copies. Reads scale; writes don't.\n2. **Sharding (partitioning)** — split data across multiple databases by key (e.g., user_id). Both reads and writes scale, but cross-shard queries become hard.\n3. **Federation (functional partitioning)** — split by function: users DB, posts DB, messages DB. Each scales independently.\n4. **Caching** — reduce database load by caching hot data in Redis/Memcached."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your web app stores user sessions in memory on each server. After adding a load balancer with round-robin, users get logged out randomly. What is the correct fix?", "shape": "mcq", "options": ["Use sticky sessions so each user always hits the same server.", "Move sessions to a shared store like Redis so any server can serve any user.", "Switch from round-robin to least-connections algorithm.", "Add more servers to reduce the chance of hitting a different one."], "answer_index": 1, "rationale": "Sticky sessions seem like a fix but they defeat horizontal scaling's fault tolerance — if that one server dies, all its users lose their sessions. The correct fix is to make servers stateless by moving sessions to shared storage (Redis). Then any server can serve any request, and the system survives server failures. This is the fundamental requirement for horizontal scaling.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "You've scaled your stateless app servers to 10 nodes behind a load balancer, but the database is now the bottleneck at 5,000 QPS. What should you do?", "shape": "mcq", "options": ["Add more app servers — they're cheap.", "Upgrade the database server to a bigger instance (vertical scaling).", "Add read replicas for read-heavy traffic, and consider sharding if writes are the bottleneck.", "Move the database to a faster disk."], "answer_index": 2, "rationale": "Adding more app servers doesn't help — they're not the bottleneck. Upgrading the database (vertical) is a temporary fix with a ceiling. The right answer is to scale the database horizontally: add read replicas (most workloads are read-heavy, so this helps a lot) and shard if writes are the bottleneck. Moving to a faster disk is another vertical-scaling band-aid.", "difficulty": "interview"}}
    ],
    "trade_offs": {"pros": ["No hard ceiling — add more nodes as needed.", "No downtime to scale — add or remove nodes dynamically.", "Fault-tolerant — lose a node, traffic shifts to others.", "Cheaper per unit — commodity hardware beats specialized big-iron."], "cons": ["Requires statelessness — significant architecture work.", "Introduces distributed systems problems — consistency, network partitions, debugging.", "More moving parts — load balancers, service discovery, distributed monitoring.", "Network latency — inter-node communication is slower than in-process calls."]},
    "failure_modes": ["Sticky sessions — defeats fault tolerance.", "Stateful services — can't scale without sticky sessions.", "Shared-resource bottleneck — if all nodes hit one database, the DB becomes the ceiling.", "Cascade failures — one slow node causes load balancer to retry on others, overloading them."],
    "common_mistakes": ["Treating 'scalability' as only about app servers — databases and caches must scale too.", "Forgetting that horizontal scaling requires statelessness from day one.", "Assuming 'add more servers' fixes everything — it doesn't fix slow code or a single bottleneck."],
    "where_you_see_it": ["Every large-scale web system.", "Every cloud-native architecture.", "Every microservices deployment."],
    "interview_prompts": ["What does it mean for a service to be 'stateless'? Why does it matter for scaling?", "Vertical vs horizontal scaling — when would you choose each?", "Your app servers scale fine but the database is the bottleneck. What do you do?"],
    "real_system_mappings": [{"system": "Netflix", "how": "Hundreds of stateless microservices on AWS EC2, auto-scaled by demand. All state in Cassandra and EVCache. Documented in their tech blog."}, {"system": "Uber", "how": "Stateless services in a service mesh, with state delegated to distributed stores (Cassandra, Schemaless)."}],
    "status": "published",
})

write_concept('retry', {
    "slug": "retry",
    "version": 2,
    "title": "Retry",
    "phase": "reliability-resilience",
    "area": "Reliability & Resilience",
    "estimated_minutes": 9,
    "difficulty": "core",
    "summary": "Retrying failed requests is the simplest reliability pattern — but done wrong, it makes failures worse. Retries must be idempotent, bounded, and use exponential backoff with jitter to avoid retry storms.",
    "why_it_matters": "Networks fail. Services fail. Transient errors are normal in distributed systems. Without retries, every transient error becomes a user-facing failure. With naive retries, a brief outage becomes a cascade that takes down the whole system. Retries done right are invisible; done wrong, they're catastrophic.",
    "prerequisites": ["idempotent-operations"],
    "related": ["circuit-breaker", "back-pressure", "timeout"],
    "used_in": ["Every distributed system.", "Every HTTP client.", "Every database driver."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "In a distributed system, transient failures are normal: a network blip, a momentary overload, a rolling deploy. Retrying the request is the natural response — but it must be done carefully.\n\nA naive retry (`if failed, try again immediately`) can make things much worse. If 10,000 clients all retry at once when a service recovers, it goes down again immediately. This is called a **retry storm**."}},
        {"type": "diagram", "id": "retry-storm", "payload": {"ascii": "  WITHOUT BACKOFF (retry storm)\n  ─────────────────────────────\n  Service goes down for 2 seconds\n  10,000 clients retry every 1ms\n  Service recovers → 20,000 req instantly\n  → service goes down again\n  → cycle repeats\n\n  WITH EXPONENTIAL BACKOFF + JITTER\n  ──────────────────────────────────\n  Client 1: retry after 100ms + random(0-50ms)\n  Client 2: retry after 200ms + random(0-50ms)\n  Client 3: retry after 400ms + random(0-50ms)\n  ...\n  Load spreads out → service recovers cleanly", "caption": "Naive retries cause storms. Exponential backoff with jitter spreads the load.", "voice_alt_text": "Two diagrams. Without backoff: when a service goes down, 10,000 clients retry immediately and continuously. When the service recovers, it gets hit with 20,000 requests instantly, goes down again, and the cycle repeats. With exponential backoff and jitter: each client retries after an exponentially increasing delay plus a random jitter, so the load spreads out over time and the service recovers cleanly."}},
        {"type": "prose", "id": "rules", "payload": {"text": "Good retries follow 4 rules:\n\n1. **Only retry idempotent operations.** If the operation might have side effects (POST to /charge), retrying might duplicate the effect. Use idempotency keys to make non-idempotent operations safely retryable.\n2. **Exponential backoff.** Wait 100ms, then 200ms, then 400ms, then 800ms. Give the failing service time to recover.\n3. **Add jitter.** Add a random component to the delay (e.g., 100ms + random(0-50ms)) so clients don't all retry at the same instant.\n4. **Bound the retries.** After 3-5 attempts, give up. Infinite retries can hang the system."}},
        {"type": "callout", "id": "circuit-breaker", "payload": {"title": "Combine with a circuit breaker", "body": "Retries handle transient failures. But if a service is down for minutes, retrying every request for minutes is wasteful and harmful. A circuit breaker detects sustained failures and stops sending requests entirely — 'trips open' — for a cooldown period, then tests if the service has recovered ('half-open'). See the Circuit Breaker lesson.", "kind": "note"}},
        {"type": "prose", "id": "status-codes", "payload": {"text": "Not all errors should be retried:\n\n- **Retry**: 429 Too Many Requests, 500/502/503/504 server errors, network timeouts.\n- **Don't retry**: 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found. These are client errors — retrying won't fix them.\n\nMost HTTP clients (axios, fetch with wrappers) support configurable retry policies. Use them."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your API client retries failed requests with a fixed 100ms delay. The downstream service goes down for 30 seconds. What happens?", "shape": "mcq", "options": ["The service recovers cleanly when it comes back up.", "All clients retry at the same 100ms intervals, causing a thundering herd that may prevent recovery.", "The retries have no effect on recovery.", "The client gives up after 3 retries."], "answer_index": 1, "rationale": "A fixed delay (no jitter) means all clients retry at the same intervals. When the service recovers, all clients hit it simultaneously — a thundering herd. This can overwhelm the recovering service and cause it to go down again. The fix is exponential backoff with jitter: each client waits a different, exponentially increasing amount, spreading the load over time.", "difficulty": "core"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "Which HTTP status code should you NOT retry?", "shape": "mcq", "options": ["503 Service Unavailable", "429 Too Many Requests", "404 Not Found", "502 Bad Gateway"], "answer_index": 2, "rationale": "404 Not Found is a client error — the resource doesn't exist. Retrying won't make it appear. 503, 429, and 502 are all transient server-side errors that may succeed on retry: 503 means the server is temporarily unavailable, 429 means you're being rate-limited (retry after the delay in the header), and 502 means a bad gateway (the upstream service is unreachable).", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Transparently handles transient failures — users don't see them.", "Simple to implement — most HTTP clients support it.", "Improves perceived reliability without infrastructure changes."], "cons": ["Retrying non-idempotent operations can duplicate side effects (double charges).", "Naive retries cause thundering herds that prevent recovery.", "Retries add latency — a request that retries 3 times takes 3x longer to fail.", "Too many retries can cascade — a slow service makes all its callers slow."]},
    "failure_modes": ["Retry storms — all clients retry simultaneously and overwhelm the recovering service.", "Retrying non-idempotent operations — duplicates side effects (payments, sends).", "Infinite retries — a single failed request hangs forever.", "Retrying client errors (4xx) — wastes resources, never succeeds."],
    "common_mistakes": ["Using a fixed retry delay instead of exponential backoff with jitter.", "Retrying every error — including 4xx client errors that will never succeed.", "Not bounding the retry count — infinite retries can hang the system.", "Forgetting to make operations idempotent before adding retries."],
    "where_you_see_it": ["Every HTTP client (axios, fetch, gRPC).", "Every database driver (connection retries).", "Every message queue consumer (retry failed messages)."],
    "interview_prompts": ["What is a retry storm, and how do you prevent it?", "Which operations are safe to retry? How do you make non-idempotent operations retryable?", "How does exponential backoff with jitter work, and why is jitter important?"],
    "real_system_mappings": [{"system": "AWS SDK", "how": "Built-in exponential backoff with jitter for all API calls. Configurable max retries (default 3) and retryable status codes."}, {"system": "gRPC", "how": "Configurable retry policy with exponential backoff, jitter, and per-method retry budgets to prevent cascading failures."}],
    "status": "published",
})

write_concept('circuit-breaker', {
    "slug": "circuit-breaker",
    "version": 2,
    "title": "Circuit Breaker",
    "phase": "reliability-resilience",
    "area": "Reliability & Resilience",
    "estimated_minutes": 11,
    "difficulty": "advanced",
    "summary": "A circuit breaker stops calling a failing service after a threshold of failures, giving it time to recover. It has three states: closed (normal), open (failing, stop calling), and half-open (testing if recovery happened). It prevents cascading failures and retry storms.",
    "why_it_matters": "Without a circuit breaker, a slow or failing downstream service drags down every service that calls it — connections pile up, threads block, and the whole system cascades into failure. A circuit breaker cuts the connection early, letting the caller fail fast and the downstream recover.",
    "prerequisites": ["retry"],
    "related": ["bulkhead", "rate-limiting", "timeout", "graceful-degradation"],
    "used_in": ["Every resilient microservice architecture.", "Every system with downstream dependencies."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "A circuit breaker is like an electrical fuse: when too many failures occur, it 'trips' and stops current from flowing. In software, this means: stop calling a failing service so it can recover, and so your service doesn't waste resources waiting for timeouts.\n\nThe pattern has three states:\n\n- **Closed** (normal): requests flow through. Failures are counted.\n- **Open** (tripped): requests fail immediately — no call is made to the downstream. This gives the downstream time to recover.\n- **Half-Open** (testing): after a cooldown, a few requests are allowed through. If they succeed, the breaker closes. If they fail, it opens again."}},
        {"type": "diagram", "id": "states", "payload": {"ascii": "  ┌─────────┐   failures > threshold   ┌─────────┐\n  │ CLOSED  │ ────────────────────────→ │  OPEN   │\n  │ (normal)│                            │ (failing)│\n  └─────────┘                            └────┬────┘\n       ↑                                       │\n       │                                       │ cooldown\n       │                                       │ expires\n       │                                       ▼\n       │           probe succeeds        ┌───────────┐\n       └──────────────────────────────── │ HALF-OPEN │\n                                        │ (testing)  │\n                                        └─────┬─────┘\n                                              │\n                                              │ probe fails\n                                              ▼\n                                         back to OPEN", "caption": "Circuit breaker state machine: Closed → Open → Half-Open → Closed/Open.", "voice_alt_text": "A state machine diagram. In the Closed state, requests flow normally and failures are counted. When failures exceed a threshold, the breaker transitions to Open — requests fail immediately without calling the downstream. After a cooldown period, it transitions to Half-Open — a few probe requests are allowed through. If probes succeed, the breaker returns to Closed. If probes fail, it goes back to Open."}},
        {"type": "prose", "id": "why", "payload": {"text": "Why is this better than just retrying?\n\n- **Fail fast**: when the breaker is open, your service fails in 1ms instead of waiting 30 seconds for a timeout. Resources (threads, connections) are freed immediately.\n- **Let the downstream recover**: if your service keeps hammering a recovering service, it can't recover. The breaker gives it breathing room.\n- **Prevent cascading failures**: without a breaker, a slow downstream service causes your service to pile up connections, which causes services that depend on you to pile up, which takes down the whole system."}},
        {"type": "callout", "id": "vs-retry", "payload": {"title": "Retry vs Circuit Breaker", "body": "Retries handle transient failures (a single bad request). Circuit breakers handle sustained failures (the service is down). Use both: retry first (for transient blips), then circuit break (if retries keep failing). Retries without a breaker cause retry storms. A breaker without retries fails too aggressively.", "kind": "note"}},
        {"type": "prose", "id": "configuration", "payload": {"text": "Typical circuit breaker configuration:\n\n- **Failure threshold**: e.g., 'open after 5 consecutive failures' or 'open after 50% failure rate over 20 requests'.\n- **Cooldown duration**: e.g., 'stay open for 30 seconds before half-open'.\n- **Half-open probes**: e.g., 'allow 3 requests through; if all succeed, close; if any fail, re-open'.\n- **Sliding window**: count failures over the last N seconds or N requests, not since startup.\n\nLibraries like Resilience4j (Java), Polly (.NET), and opossum (Node.js) implement this with sensible defaults."}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your service calls a downstream API that starts timing out. Without a circuit breaker, what happens?", "shape": "mcq", "options": ["Your service fails fast and recovers quickly.", "Your service accumulates blocked connections, eventually running out of threads/connections and failing entirely.", "The downstream service recovers on its own.", "Nothing — timeouts handle everything."], "answer_index": 1, "rationale": "Without a circuit breaker, every call to the failing downstream service waits for its timeout (e.g., 30 seconds). During this time, the calling service holds a thread and a connection. As more requests come in, more threads block, until the calling service runs out of threads/connections and fails entirely — even though it was the downstream that was broken. This is a cascading failure. A circuit breaker would fail fast (1ms) when the downstream is down, freeing resources immediately.", "difficulty": "interview"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "A circuit breaker is in the Open state. A request comes in. What happens?", "shape": "mcq", "options": ["The request is sent to the downstream service and waits for a timeout.", "The request fails immediately (in ~1ms) without calling the downstream.", "The request is queued until the breaker closes.", "The request is retried 3 times."], "answer_index": 1, "rationale": "In the Open state, the circuit breaker fails the request immediately — it does not call the downstream service at all. This is the entire point of the pattern: fail fast (~1ms) instead of waiting for a timeout (~30s), freeing up threads and connections. The request either gets a fallback response (graceful degradation) or an error. The breaker only starts sending requests again after the cooldown expires and it enters the Half-Open state to test recovery.", "difficulty": "core"}}
    ],
    "trade_offs": {"pros": ["Prevents cascading failures — one broken service doesn't take down everything.", "Fails fast — frees resources instead of waiting for timeouts.", "Gives downstream services time to recover.", "Self-healing — automatically tests for recovery (half-open)."], "cons": ["Adds complexity — another state to reason about.", "Can cause 'flapping' if the threshold is too sensitive.", "Requires tuning — wrong thresholds cause false trips or missed failures.", "Doesn't help with non-transient failures (e.g., a 404)."]},
    "failure_modes": ["Threshold too sensitive — breaker trips on normal variance, causing unnecessary failures.", "Threshold too insensitive — breaker never trips, cascading failure still happens.", "Cooldown too short — downstream doesn't have time to recover before being hammered again.", "No fallback — when the breaker is open, the caller needs a fallback (cached data, default value, error."],
    "common_mistakes": ["Treating the breaker as a retry mechanism — it's the opposite, it stops retries.", "Not providing a fallback — when the breaker is open, what does the user see?", "Setting the threshold too low — normal latency variance trips the breaker.", "Forgetting to monitor breaker state — you need to know when breakers are open."],
    "where_you_see_it": ["Every resilient microservice architecture.", "Service meshes (Istio, Linkerd) implement circuit breaking at the sidecar.", "Cloud SDKs (AWS, GCP) have built-in circuit breakers for API calls."],
    "interview_prompts": ["What is a circuit breaker? How does it differ from a retry?", "Explain the three states of a circuit breaker.", "How do you choose the failure threshold and cooldown duration?", "What happens when the breaker is open — what does the caller do?"],
    "real_system_mappings": [{"system": "Netflix Hystrix", "how": "Pioneered circuit breaking in microservices. Now deprecated in favor of Resilience4j, but the pattern is universal."}, {"system": "Istio service mesh", "how": "Implements circuit breaking at the sidecar (Envoy proxy), so applications don't need circuit breaker code."}],
    "status": "published",
})

write_concept('bulkhead', {
    "slug": "bulkhead",
    "version": 2,
    "title": "Bulkhead",
    "phase": "reliability-resilience",
    "area": "Reliability & Resilience",
    "estimated_minutes": 9,
    "difficulty": "advanced",
    "summary": "A bulkhead isolates resources so a failure in one part of the system doesn't take down everything else. Like watertight compartments in a ship's hull, if one compartment floods, the ship stays afloat. In software: separate thread pools, connection pools, or processes for different services or workloads.",
    "why_it_matters": "Without bulkheads, all your services share the same thread pool and connection pool. One slow downstream service consumes all threads, and your service can't handle requests for other (healthy) downstreams. Bulkheads isolate failures so only the affected part of the system degrades.",
    "prerequisites": ["circuit-breaker"],
    "related": ["circuit-breaker", "graceful-degradation"],
    "used_in": ["Resilient microservice architectures.", "Systems with multiple downstream dependencies."],
    "blocks": [
        {"type": "prose", "id": "intro", "payload": {"text": "The name comes from ship design: a ship's hull is divided into watertight compartments (bulkheads). If one compartment floods, the door is closed and the ship stays afloat. The damage is isolated.\n\nIn software, the same principle applies: if your service calls 3 downstream services (A, B, C), and they all share one thread pool, a failure in A can consume all threads and prevent B and C from being served. A bulkhead gives each downstream its own pool — A's failure only affects A's pool."}},
        {"type": "diagram", "id": "bulkhead", "payload": {"ascii": "  WITHOUT BULKHEAD (shared pool)\n  ──────────────────────────────\n  Incoming → [ Thread Pool (100) ] → Service A (slow!)\n                              ↓     Service B (fast)\n                              ↓     Service C (fast)\n  Service A consumes all 100 threads.\n  Services B and C are starved.\n  → entire service is down.\n\n  WITH BULKHEAD (separate pools)\n  ──────────────────────────────\n  Incoming → [ Pool A (30) ] → Service A (slow)\n           → [ Pool B (30) ] → Service B (fast)\n           → [ Pool C (40) ] → Service C (fast)\n  Service A's pool saturates, but B and C\n  continue working normally.\n  → only A is degraded.", "caption": "Without bulkheads, one slow service starves everything. With bulkheads, each service is isolated.", "voice_alt_text": "Two diagrams. Without a bulkhead: all three downstream services share one pool of 100 threads. When service A becomes slow, it consumes all 100 threads, and services B and C are starved — the entire service is down. With a bulkhead: each service has its own pool (30 for A, 30 for B, 40 for C). When service A saturates its pool, only A is degraded — services B and C continue working normally."}},
        {"type": "prose", "id": "isolation", "payload": {"text": "Bulkheads can be implemented at different levels:\n\n- **Thread pools**: separate pool per downstream service. Most common.\n- **Connection pools**: separate HTTP/TCP connection pool per downstream.\n- **Processes**: separate processes (or containers) per service type. Strongest isolation.\n- **Machines**: separate servers per workload. Physical isolation.\n\nThe stronger the isolation, the more resource-expensive. Thread pools are the sweet spot for most cases."}},
        {"type": "callout", "id": "combine", "payload": {"title": "Bulkhead + Circuit Breaker", "body": "Bulkheads limit the blast radius. Circuit breakers stop calling a failing service entirely. Together: the circuit breaker prevents new calls to a failing service, and the bulkhead ensures that even if the breaker is slow to trip, other services aren't affected. This combination is the foundation of resilient microservice architecture.", "kind": "success"}},
        {"type": "quiz", "id": "q1", "payload": {"question": "Your service has a single thread pool of 200 threads and calls 3 downstream services. One downstream starts responding slowly. What happens without a bulkhead?", "shape": "mcq", "options": ["Only requests to the slow downstream are affected.", "The slow downstream consumes all 200 threads, and requests to the other two downstreams also fail.", "The service automatically scales up more threads.", "Nothing — 200 threads is enough for anyone."], "answer_index": 1, "rationale": "Without a bulkhead, all three downstreams share the same 200-thread pool. The slow downstream causes each of its requests to hold a thread for longer (waiting for the slow response). As more requests come in, all 200 threads eventually get consumed by the slow downstream, leaving no threads for the other two — they fail too, even though they're healthy. This is why bulkheads (separate thread pools per downstream) are essential in resilient architecture.", "difficulty": "interview"}},
        {"type": "quiz", "id": "q2", "payload": {"question": "What is the relationship between bulkheads and circuit breakers?", "shape": "mcq", "options": ["They are the same thing — different names for one pattern.", "Bulkheads limit the blast radius; circuit breakers stop calling a failing service entirely. They complement each other.", "Circuit breakers replace bulkheads — you only need one.", "Bulkheads replace circuit breakers."], "answer_index": 1, "rationale": "Bulkheads and circuit breakers are complementary, not alternatives. A bulkhead limits the blast radius of a failure — if one downstream is slow, only its thread pool is affected, not the others. A circuit breaker stops calling a failing service entirely — it 'trips open' after enough failures. Together: the breaker prevents new calls, and the bulkhead ensures that even before the breaker trips, other services aren't starved. Most resilient systems use both.", "difficulty": "advanced"}}
    ],
    "trade_offs": {"pros": ["Isolates failures — one broken downstream doesn't take down everything.", "Allows partial degradation — some features work while others fail.", "Composable with circuit breakers for layered resilience."], "cons": ["More resource overhead — separate pools means more idle threads.", "Harder to tune — how big should each pool be?", "Adds complexity — more moving parts to monitor and debug.", "Can cause under-utilization — if one pool is idle while another is saturated, you can't borrow."]},
    "failure_modes": ["Pool too small — legitimate traffic gets rejected even when the downstream is healthy.", "Pool too large — too many concurrent calls overwhelm the downstream.", "No monitoring — if you don't know a pool is saturated, you can't diagnose the failure."],
    "common_mistakes": ["Using a single shared pool for all downstreams — defeats the purpose.", "Making pools too small — causes false failures under normal load spikes.", "Forgetting to monitor pool utilization — you need to know when pools are near saturation."],
    "where_you_see_it": ["Resilient microservice architectures.", "Service meshes (Istio, Linkerd) with per-service connection pools.", "Hystrix/Resilience4j bulkhead patterns in Java microservices."],
    "interview_prompts": ["What is a bulkhead pattern? How does it differ from a circuit breaker?", "Why would you use separate thread pools for different downstream services?", "How do you decide the size of each bulkhead pool?"],
    "real_system_mappings": [{"system": "Netflix Hystrix", "how": "Popularized bulkheads in microservices: each downstream had its own thread pool, so a slow dependency couldn't starve others."}, {"system": "Envoy proxy (Istio)", "how": "Configures per-upstream connection pools and circuit breakers at the sidecar, isolating failures without application code changes."}],
    "status": "published",
})

print("\n✅ Networking/Scaling/Reliability concepts written")
