'use client';

import { useEffect, useRef, useState, memo, useId } from 'react';
import { cn } from '@/lib/utils';


function compactAutoGeneratedMermaid(code: string): string {
  const nodeMatches = Array.from(code.matchAll(/\b(N\d+)\["([\s\S]*?)"\]/g));
  if (nodeMatches.length < 10 || !/\bN\d+\s*--/.test(code)) return code;

  const unique: string[] = [];
  for (const m of nodeMatches) {
    const raw = m[2].replace(/\\"/g, '"').replace(/\s+/g, ' ').trim();
    if (raw && !unique.includes(raw)) unique.push(raw);
  }
  if (unique.length < 10) return code;

  const count = Math.min(6, Math.max(3, Math.ceil(unique.length / 10)));
  const per = Math.ceil(unique.length / count);
  const groups: string[][] = [];
  for (let i = 0; i < unique.length; i += per) groups.push(unique.slice(i, i + per));

  const labels = groups.map((g) => {
    const text = g.join(' · ').replace(/\[|\]|\{|\}|\(|\)/g, '').trim();
    if (text.length <= 72) return text;
    const short = text.slice(0, 68);
    const cut = short.lastIndexOf(' · ');
    return `${(cut > 24 ? short.slice(0, cut) : short).trim()}…`;
  });

  const lines = ['flowchart LR'];
  labels.forEach((label, i) => lines.push(`  G${i}["${label.replace(/"/g, "'")}"]`));
  for (let i = 0; i < labels.length - 1; i++) lines.push(`  G${i} --> G${i + 1}`);
  return lines.join('\n');
}

interface MermaidBlockProps {
  code: string;
  caption?: string;
  alt_text?: string;
}

function MermaidBlockInner({ code, caption, alt_text }: MermaidBlockProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [mounted, setMounted] = useState(false);

  // useId() produces a deterministic, hydration-safe unique ID per component instance.
  const reactId = useId();
  // Sanitize for Mermaid (which only accepts alphanumeric + hyphens/underscores).
  const mermaidId = `m${reactId.replace(/[^a-zA-Z0-9-]/g, '')}`;

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted) return;

    let cancelled = false;

    (async () => {
      try {
        // Dynamic import — Mermaid is only loaded on the client, never during SSR.
        const mermaid = (await import('mermaid')).default;
        mermaid.initialize({
          startOnLoad: false,
          theme: 'base',
          securityLevel: 'strict',
          fontFamily: 'ui-sans-serif, system-ui, sans-serif',
          themeVariables: {
            primaryColor: '#f5ead7',
            primaryTextColor: '#251f18',
            primaryBorderColor: '#b98a49',
            lineColor: '#8f8068',
            secondaryColor: '#e8f0e8',
            tertiaryColor: '#f0ece4',
          },
          flowchart: {
            useMaxWidth: true,
            htmlLabels: false,
            curve: 'linear',
            nodeSpacing: 40,
            rankSpacing: 48,
            wrappingWidth: 180,
            padding: 8,
          },
          sequence: { useMaxWidth: true, diagramMarginX: 12, diagramMarginY: 10, actorMargin: 28, messageMargin: 22 },
          gantt: { useMaxWidth: true },
        });

        // Long auto-generated flowcharts frequently become absurdly tall.
        // For dense flowcharts, prefer a horizontal layout so they remain
        // legible inside a bounded reading surface. Preserve sequence/state diagrams.
        let safeCode = compactAutoGeneratedMermaid(code);
        if (/^(flowchart|graph)\s+(TB|TD)\b/i.test(safeCode.trim()) && safeCode.split('\n').length > 9) {
          safeCode = safeCode.replace(/^(flowchart|graph)\s+(TB|TD)\b/i, '$1 LR');
        }
        safeCode = safeCode.replace(/<br\s*\/?>(?=\s*)/gi, ' ');

        const { svg: rendered } = await mermaid.render(mermaidId, safeCode);

        if (!cancelled) {
          setSvg(rendered);
          setError(null);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to render diagram');
          setSvg(null);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [code, mounted, mermaidId]);

  if (!mounted) {
    return (
      <div className="my-4 rounded-lg border border-border bg-surface p-8 text-center">
        <p className="text-sm text-text-muted">Loading diagram…</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="my-4">
        <div className="rounded-lg border border-warning bg-warning-soft p-4">
          <p className="text-sm text-warning">Diagram could not be rendered.</p>
          {alt_text && (
            <p className="mt-2 text-xs text-text-secondary">{alt_text}</p>
          )}
        </div>
        {caption && <p className="mt-1 text-xs text-text-muted">{caption}</p>}
      </div>
    );
  }

  return (
    <figure className="my-5">
      <div
        ref={containerRef}
        className={cn(
          'nocap-mermaid-shell overflow-auto rounded-lg border border-border bg-surface p-3 sm:p-4 max-h-[28rem] min-h-[8rem]',
          '[&>svg]:mx-auto [&>svg]:block [&>svg]:h-auto [&>svg]:max-w-full',
          '[&>svg]:min-h-0 [&>svg]:w-auto'
        )}

        aria-label={alt_text || caption || 'Diagram'}
        role="img"
        dangerouslySetInnerHTML={svg ? { __html: svg } : undefined}
      />
      {caption && (
        <figcaption className="mt-2 text-center text-xs text-text-muted">
          {caption}
        </figcaption>
      )}
    </figure>
  );
}

export const MermaidBlock = memo(MermaidBlockInner);
